var QAList = new Array(
//-----------------------------------------------------V-----------------------------------------------------
{que:"開く"					,ans:"あく"						,tip:"(something) open"							,group:1	,accr:0},
{que:"閉まる"				,ans:"しまる"					,tip:"(something) close"						,group:1	,accr:0},
{que:"開ける"				,ans:"あける"					,tip:"to open"									,group:2	,accr:0},
{que:"閉める"				,ans:"しめる"					,tip:"close"									,group:2	,accr:0},
{que:"歩く"					,ans:"あるく"					,tip:"to walk"									,group:3	,accr:0},
{que:"走る"					,ans:"はしる"					,tip:"run"										,group:3	,accr:0},
{que:"動く"					,ans:"うごく"					,tip:"(something) move"							,group:4	,accr:0},
{que:"止まる"				,ans:"とまる"					,tip:"(something) stop"							,group:4	,accr:0},
{que:"売る"					,ans:"うる"						,tip:"to sell"									,group:5	,accr:0},
{que:"買う"					,ans:"かう"						,tip:"to buy"									,group:5	,accr:0},
{que:"起きる"				,ans:"おきる"					,tip:"(something) get up"						,group:6	,accr:0},
{que:"寝る"					,ans:"ねる"						,tip:"go to bed"								,group:6	,accr:0},
{que:"押す"					,ans:"おす"						,tip:"to push"									,group:7	,accr:0},
{que:"引く"					,ans:"ひく"						,tip:"pull/draw"								,group:7	,accr:0},
{que:"降りる"				,ans:"おりる"					,tip:"to get off/to get out (of)"				,group:8	,accr:0},	//上がる/上る/登る
{que:"乗る"					,ans:"のる"						,tip:"take/ride on"								,group:8	,accr:0},
{que:"終わる"				,ans:"おわる"					,tip:"(something) be finished"					,group:9	,accr:0},
{que:"始まる"				,ans:"はじまる"					,tip:"(something) begin"						,group:9	,accr:0},
{que:"返す"					,ans:"かえす"					,tip:"to return"								,group:10	,accr:0},
{que:"借りる"				,ans:"かりる"					,tip:"borrow"									,group:10	,accr:0},
{que:"貸す"					,ans:"かす"						,tip:"to lend"									,group:10	,accr:0},
{que:"書く"					,ans:"かく"						,tip:"to write"									,group:11	,accr:0},
{que:"読む"					,ans:"よむ"						,tip:"read"										,group:11	,accr:0},
{que:"掛ける"				,ans:"かける"					,tip:"to wear(a glass)"							,group:12	,accr:0},	//外す
{que:"切る"					,ans:"きる"						,tip:"cut"										,group:12	,accr:0},	//結ぶ/続ける/繋ぐ
{que:"被る"					,ans:"かぶる"					,tip:"put on (hat)"								,group:13	,accr:0},
{que:"着る"					,ans:"きる"						,tip:"to put (tops) on/to wear (tops)"			,group:13	,accr:0},
{que:"穿く/履く"			,ans:"はく"						,tip:"to put (buttoms) on/wear (buttoms)"		,group:13	,accr:0},
{que:"脱ぐ"					,ans:"ぬぐ"						,tip:"take off"									,group:13	,accr:0},
{que:"帰る"					,ans:"かえる"					,tip:"to go back/to be back"					,group:14	,accr:0},	//行く/往く
{que:"来る"					,ans:"くる"						,tip:"to come"									,group:14	,accr:0},	//行く/往く
{que:"聞く"					,ans:"きく"						,tip:"listen to/ask"							,group:15	,accr:0},
{que:"話す"					,ans:"はなす"					,tip:"talk/speak"								,group:15	,accr:0},
{que:"消す"					,ans:"けす"						,tip:"turn off"									,group:16	,accr:0},
{que:"点ける"				,ans:"つける"					,tip:"turn on"									,group:16	,accr:0},
{que:"生きる"				,ans:"いきる"					,tip:"live"										,group:17	,accr:0},
{que:"死ぬ"					,ans:"しぬ"						,tip:"die"										,group:17	,accr:0},
{que:"生まれる"				,ans:"うまれる"					,tip:"be born"									,group:17	,accr:0},
{que:"覚える"				,ans:"おぼえる"					,tip:"to memorize"								,group:18	,accr:0},	//忘れる
{que:"思い出す"				,ans:"おもいだす"				,tip:"recall/remember"							,group:18	,accr:0},
{que:"降る"					,ans:"ふる"						,tip:"fall/come down/rain"						,group:19	,accr:0},	//照る/止む
{que:"曇る"					,ans:"くもる"					,tip:"become cloudy"							,group:19	,accr:0},
{que:"晴れる"				,ans:"はれる"					,tip:"clear up"									,group:19	,accr:0},
{que:"壊す"					,ans:"こわす"					,tip:"break"									,group:20	,accr:0},
{que:"直す"					,ans:"なおす"					,tip:"repair"									,group:20	,accr:0},
{que:"答える"				,ans:"こたえる"					,tip:"answer"									,group:21	,accr:0},	//問う
{que:"尋ねる"				,ans:"たずねる"					,tip:"ask"										,group:21	,accr:0},
{que:"入れる"				,ans:"いれる"					,tip:"to put (any) in"							,group:22	,accr:0},
{que:"出す"					,ans:"だす"						,tip:"put out"									,group:22	,accr:0},
{que:"叱る"					,ans:"しかる"					,tip:"scold"									,group:23	,accr:0},
{que:"誉める"				,ans:"ほめる"					,tip:"give compliment"							,group:23	,accr:0},
{que:"送る"					,ans:"おくる"					,tip:"to send"									,group:24	,accr:0},
{que:"迎える"				,ans:"むかえる"					,tip:"pick (person) up"							,group:24	,accr:0},
{que:"太る"					,ans:"ふとる"					,tip:"get fat"									,group:25	,accr:0},
{que:"や＿る"				,ans:"やせる"					,tip:"lose weight"								,group:25	,accr:0},
{que:"輸出する"				,ans:"ゆしゅつする"				,tip:"export"									,group:26	,accr:0},
{que:"輸入する"				,ans:"ゆにゅうする"				,tip:"import"									,group:26	,accr:0},
{que:"会う"					,ans:"あう"						,tip:"to meet"									,group:27	,accr:0},
{que:"別れる"				,ans:"わかれる"					,tip:"separate"									,group:27	,accr:0},
{que:"片付ける"				,ans:"かたづける"				,tip:"put in order/tidy up"						,group:28	,accr:0},
{que:"片付く"				,ans:"かたづく"					,tip:"(something) put in order"					,group:28	,accr:0},
{que:"あ＿る"				,ans:"あげる"					,tip:"to give"									,group:0	,accr:0},
{que:"遊ぶ"					,ans:"あそぶ"					,tip:"to have fun/to play"						,group:0	,accr:0},
{que:"洗う"					,ans:"あらう"					,tip:"to wash"									,group:0	,accr:0},
{que:"＿る"					,ans:"ある"						,tip:"to be/to have"							,group:0	,accr:0},
{que:"言う"					,ans:"いう"						,tip:"to say/to talk"							,group:0	,accr:0},
{que:"要る"					,ans:"いる"						,tip:"to need/to be necessary"					,group:0	,accr:0},
{que:"歌う"					,ans:"うたう"					,tip:"to sing"									,group:0	,accr:0},
{que:"置く"					,ans:"おく"						,tip:"to put"									,group:0	,accr:0},
{que:"行う"					,ans:"おこなう"					,tip:"to do/to operate"							,group:0	,accr:0},
{que:"泳ぐ"					,ans:"およぐ"					,tip:"to swim"									,group:0	,accr:0},
{que:"掛ける"				,ans:"かける"					,tip:"to telephone"								,group:0	,accr:0},	//外す
{que:"消える"				,ans:"きえる"					,tip:"be extinguished"							,group:0	,accr:0},	//現れる/点る/灯る/燃える/点く/熾る
{que:"困る"					,ans:"こまる"					,tip:"be in trouble"							,group:0	,accr:0},
{que:"知る"					,ans:"しる"						,tip:"know"										,group:0	,accr:0},
{que:"住む"					,ans:"すむ"						,tip:"live"										,group:0	,accr:0},
{que:"立つ"					,ans:"たつ"						,tip:"stand"									,group:0	,accr:0},	//座る
{que:"頼む"					,ans:"たのむ"					,tip:"ask/request"								,group:0	,accr:0},
{que:"食べる"				,ans:"たべる"					,tip:"eat"										,group:0	,accr:0},
{que:"使う"					,ans:"つかう"					,tip:"use"										,group:0	,accr:0},
{que:"疲れる"				,ans:"つかれる"					,tip:"be tired"									,group:0	,accr:0},
{que:"着く"					,ans:"つく"						,tip:"arrive"									,group:0	,accr:0},
{que:"作る"					,ans:"つくる"					,tip:"make"										,group:0	,accr:0},
{que:"勤める"				,ans:"つとめる"					,tip:"work for"									,group:0	,accr:0},
{que:"出かける"				,ans:"でかける"					,tip:"go out"									,group:0	,accr:0},
{que:"出来る"				,ans:"できる"					,tip:"can"										,group:0	,accr:0},
{que:"飛ぶ"					,ans:"とぶ"						,tip:"fly"										,group:0	,accr:0},
{que:"取る"					,ans:"とる"						,tip:"take"										,group:0	,accr:0},
{que:"習う"					,ans:"ならう"					,tip:"learn"									,group:0	,accr:0},	//教える
{que:"並ぶ"					,ans:"ならぶ"					,tip:"make a line"								,group:0	,accr:0},
{que:"並べる"				,ans:"ならべる"					,tip:"line up/display"							,group:0	,accr:0},
{que:"＿る"					,ans:"なる"						,tip:"become"									,group:0	,accr:0},
{que:"飲む"					,ans:"のむ"						,tip:"drink"									,group:0	,accr:0},	//吐く/吸う
{que:"入る"					,ans:"はいる"					,tip:"enter"									,group:0	,accr:0},	//入る/出る
{que:"始める"				,ans:"はじめる"					,tip:"start"									,group:0	,accr:0},	//終える
{que:"働く"					,ans:"はたらく"					,tip:"work"										,group:0	,accr:0},
{que:"貼る"					,ans:"はる"						,tip:"paste/put some on"						,group:0	,accr:0},	//剥がす/張る
{que:"弾く"					,ans:"ひく"						,tip:"play (instrument)"						,group:0	,accr:0},
{que:"曲がる"				,ans:"まがる"					,tip:"turn"										,group:0	,accr:0},
{que:"磨く"					,ans:"みがく"					,tip:"brush"									,group:0	,accr:0},
{que:"見る"					,ans:"みる"						,tip:"look"										,group:0	,accr:0},
{que:"呼ぶ"					,ans:"よぶ"						,tip:"call"										,group:0	,accr:0},
{que:"渡す"					,ans:"わたす"					,tip:"hand over"								,group:0	,accr:0},
{que:"渡る"					,ans:"わたる"					,tip:"cross"									,group:0	,accr:0},
{que:"挨拶する"				,ans:"あいさつする"				,tip:"greet"									,group:0	,accr:0},
{que:"合う"					,ans:"あう"						,tip:"match/suit"								,group:0	,accr:0},
{que:"空く"					,ans:"あく"						,tip:"become vacant/to be empty"				,group:0	,accr:0},
{que:"謝る"					,ans:"あやまる"					,tip:"apologize"								,group:0	,accr:0},
{que:"安心する"				,ans:"あんしんする"				,tip:"feel at ease"								,group:0	,accr:0},
{que:"苛める"				,ans:"いじめる"					,tip:"persecute/bully"							,group:0	,accr:0},
{que:"致す"					,ans:"いたす"					,tip:"do (modest)"								,group:0	,accr:0},
{que:"祈る"					,ans:"いのる"					,tip:"pray"										,group:0	,accr:0},
{que:"植える"				,ans:"うえる"					,tip:"plant"									,group:0	,accr:0},
{que:"訪う"					,ans:"うかがう"					,tip:"visit"									,group:0	,accr:0},
{que:"受ける"				,ans:"うける"					,tip:"take/receive"								,group:0	,accr:0},
{que:"写す"					,ans:"うつす"					,tip:"copy/photograph"							,group:0	,accr:0},
{que:"移る"					,ans:"うつる"					,tip:"move/change"								,group:0	,accr:0},
{que:"選ぶ"					,ans:"えらぶ"					,tip:"select/choose"							,group:0	,accr:0},
{que:"お＿＿＿＿る"			,ans:"おいでになる"				,tip:"come/go/be (honorific)"					,group:0	,accr:0},
{que:"起こす"				,ans:"おこす"					,tip:"wake (someone) up"						,group:0	,accr:0},
{que:"怒る"					,ans:"おこる"					,tip:"get angry"								,group:0	,accr:0},
{que:"踊る"					,ans:"おどる"					,tip:"dance"									,group:0	,accr:0},
{que:"驚く"					,ans:"おどろく"					,tip:"surprise"									,group:0	,accr:0},
{que:"思う"					,ans:"おもう"					,tip:"think"									,group:0	,accr:0},
{que:"か＿る"				,ans:"かかる"					,tip:"take (time)/cost"							,group:0	,accr:0},
{que:"飾る"					,ans:"かざる"					,tip:"decorate"									,group:0	,accr:0},
{que:"変わる"				,ans:"かわる"					,tip:"change"									,group:0	,accr:0},
{que:"考える"				,ans:"かんがえる"				,tip:"consider/think"							,group:0	,accr:0},
{que:"聞こえる"				,ans:"きこえる"					,tip:"audible/can hear"							,group:0	,accr:0},
{que:"決まる"				,ans:"きまる"					,tip:"(something) be decide"					,group:0	,accr:0},
{que:"決める"				,ans:"きめる"					,tip:"decide"									,group:0	,accr:0},
{que:"比べる"				,ans:"くらべる"					,tip:"compare"									,group:0	,accr:0},
{que:"下さる"				,ans:"くださる"					,tip:"give (honorific)"							,group:0	,accr:0},
{que:"見物する"				,ans:"けんぶつする"				,tip:"sightseeing"								,group:0	,accr:0},
{que:"混む/込む"			,ans:"こむ"						,tip:"to be crowed"								,group:0	,accr:0},
{que:"ご覧になる"			,ans:"ごらんになる"				,tip:"see/inspect(honorific)"					,group:0	,accr:0},
{que:"探す"					,ans:"さがす"					,tip:"look for"									,group:0	,accr:0},
{que:"探る"					,ans:"さぐる"					,tip:"search"									,group:0	,accr:0},
{que:"咲く"					,ans:"さく"						,tip:"bloom"									,group:0	,accr:0},
{que:"差し上げる"			,ans:"さしあげる"				,tip:"give (modest)"							,group:0	,accr:0},
{que:"騒ぐ"					,ans:"さわぐ"					,tip:"make a noise"								,group:0	,accr:0},
{que:"触る"					,ans:"さわる"					,tip:"touch"									,group:0	,accr:0},
{que:"出発する"				,ans:"しゅっぱつする"			,tip:"depart"									,group:0	,accr:0},
{que:"招待する"				,ans:"しょうたいする"			,tip:"invite"									,group:0	,accr:0},
{que:"知らせる"				,ans:"しらせる"					,tip:"let know/tell"							,group:0	,accr:0},
{que:"調べる"				,ans:"しらべる"					,tip:"investigate"								,group:0	,accr:0},
{que:"準備する"				,ans:"じゅんびする"				,tip:"prepare"									,group:0	,accr:0},
{que:"過ぎる"				,ans:"すぎる"					,tip:"pass"										,group:0	,accr:0},
{que:"滑る"					,ans:"すべる"					,tip:"slide/slip"								,group:0	,accr:0},
{que:"済む"					,ans:"すむ"						,tip:"end"										,group:0	,accr:0},
{que:"育てる"				,ans:"そだてる"					,tip:"grow"										,group:0	,accr:0},
{que:"倒れる"				,ans:"たおれる"					,tip:"(something) fall down"					,group:0	,accr:0},
{que:"訪ねる"				,ans:"たずねる"					,tip:"visit"									,group:0	,accr:0},
{que:"立てる"				,ans:"たてる"					,tip:"raise/set up"								,group:0	,accr:0},
{que:"建てる"				,ans:"たてる"					,tip:"build"									,group:0	,accr:0},
{que:"た＿る"				,ans:"たりる"					,tip:"be enough"								,group:0	,accr:0},
{que:"伝える"				,ans:"つたえる"					,tip:"tell/report"								,group:0	,accr:0},
{que:"包む"					,ans:"つつむ"					,tip:"wrap/pack"								,group:0	,accr:0},
{que:"続く"					,ans:"つづく"					,tip:"(something) continued"					,group:0	,accr:0},
{que:"続ける"				,ans:"つづける"					,tip:"continue"									,group:0	,accr:0},
{que:"釣る"					,ans:"つる"						,tip:"fish/angle"								,group:0	,accr:0},
{que:"手伝う"				,ans:"てつだう"					,tip:"help"										,group:0	,accr:0},
{que:"通る"					,ans:"とおる"					,tip:"pass/go along"							,group:0	,accr:0},
{que:"届ける"				,ans:"とどける"					,tip:"deliver"									,group:0	,accr:0},
{que:"取り替える"			,ans:"とりかえる"				,tip:"exchange"									,group:0	,accr:0},
{que:"直る"					,ans:"なおる"					,tip:"(something) repaired"						,group:0	,accr:0},
{que:"治る"					,ans:"なおる"					,tip:"(something/someone) get well"				,group:0	,accr:0},
{que:"鳴く"					,ans:"なく"						,tip:"sing/mew/moo etc."						,group:0	,accr:0},
{que:"無くす"				,ans:"なくす"					,tip:"lose"										,group:0	,accr:0},
{que:"無くなる"				,ans:"なくなる"					,tip:"be lost"									,group:0	,accr:0},
{que:"亡くなる"				,ans:"なくなる"					,tip:"passed away"								,group:0	,accr:0},
{que:"投げる"				,ans:"なげる"					,tip:"throw"									,group:0	,accr:0},
{que:"慣れる"				,ans:"なれる"					,tip:"get used to"								,group:0	,accr:0},
{que:"逃げる"				,ans:"にげる"					,tip:"run away"									,group:0	,accr:0},
{que:"盗む"					,ans:"ぬすむ"					,tip:"steal"									,group:0	,accr:0},
{que:"塗る"					,ans:"ぬる"						,tip:"paint"									,group:0	,accr:0},
{que:"濡れる"				,ans:"ぬれる"					,tip:"get wet"									,group:0	,accr:0},
{que:"眠る"					,ans:"ねむる"					,tip:"sleep"									,group:0	,accr:0},
{que:"残る"					,ans:"のこる"					,tip:"remain"									,group:0	,accr:0},
{que:"乗り換える"			,ans:"のりかえる"				,tip:"transfer"									,group:0	,accr:0},
{que:"冷える"				,ans:"ひえる"					,tip:"get cold"									,group:0	,accr:0},
{que:"引っ越す"				,ans:"ひっこす"					,tip:"move to (house)"							,group:0	,accr:0},
{que:"拾う"					,ans:"ひろう"					,tip:"pick up"									,group:0	,accr:0},
{que:"翻訳する"				,ans:"ほんやくする"				,tip:"translate"								,group:0	,accr:0},
{que:"参る"					,ans:"まいる"					,tip:"come (modest)"							,group:0	,accr:0},
{que:"負ける"				,ans:"まける"					,tip:"lose"										,group:0	,accr:0},
{que:"間違える"				,ans:"まちがえる"				,tip:"mistake"									,group:0	,accr:0},
{que:"間に合う"				,ans:"まにあう"					,tip:"be in time"								,group:0	,accr:0},
{que:"回る"					,ans:"まわる"					,tip:"go round"									,group:0	,accr:0},
{que:"見つかる"				,ans:"みつかる"					,tip:"(something) be found"						,group:0	,accr:0},
{que:"見つける"				,ans:"みつける"					,tip:"find out"									,group:0	,accr:0},
{que:"召し上がる"			,ans:"めしあがる"				,tip:"eat (honorific)"							,group:0	,accr:0},
{que:"申し上げる"			,ans:"もうしあげる"				,tip:"say (honorific)"							,group:0	,accr:0},
{que:"申す"					,ans:"もうす"					,tip:"say (modest)"								,group:0	,accr:0},
{que:"持つ"					,ans:"もつ"						,tip:"have/take/hold/carry"						,group:0	,accr:0},
{que:"も＿う"				,ans:"もらう"					,tip:"receive"									,group:0	,accr:0},
{que:"焼ける"				,ans:"やける"					,tip:"be burned"								,group:0	,accr:0},
{que:"揺れる"				,ans:"ゆれる"					,tip:"shake/quake"								,group:0	,accr:0},
{que:"汚れる"				,ans:"よごれる"					,tip:"get dirty"								,group:0	,accr:0},
{que:"喜ぶ"					,ans:"よろこぶ"					,tip:"be glad"									,group:0	,accr:0},
{que:"利用する"				,ans:"りようする"				,tip:"use"										,group:0	,accr:0},
{que:"沸かす"				,ans:"わかす"					,tip:"boil"										,group:0	,accr:0},
{que:"分かる"				,ans:"わかる"					,tip:"understand"								,group:0	,accr:0},
{que:"沸く"					,ans:"わく"						,tip:"(something) boil"							,group:0	,accr:0},
//----------------------------------------------------ADJ----------------------------------------------------
{que:"暖かい"				,ans:"あたたかい"				,tip:"warm"										,group:101	,accr:0},
{que:"涼しい"				,ans:"すずしい"					,tip:"cool"										,group:101	,accr:0},
{que:"暑い"					,ans:"あつい"					,tip:"hot (temperature)"						,group:101	,accr:0},
{que:"寒い"					,ans:"さむい"					,tip:"cold (temperature)"						,group:101	,accr:0},
{que:"熱い"					,ans:"あつい"					,tip:"hot (heat)"								,group:102	,accr:0},	//温い
{que:"冷たい"				,ans:"つめたい"					,tip:"cold (heat)"								,group:102	,accr:0},
{que:"新しい"				,ans:"あたらしい"				,tip:"new"										,group:103	,accr:0},
{que:"古い"					,ans:"ふるい"					,tip:"old"										,group:103	,accr:0},
{que:"赤い"					,ans:"あかい"					,tip:"red"										,group:104	,accr:0},
{que:"黄色い"				,ans:"きいろい"					,tip:"yellow"									,group:104	,accr:0},
{que:"忙しい"				,ans:"いそがしい"				,tip:"busy"										,group:105	,accr:0},
{que:"暇な"					,ans:"ひまな"					,tip:"being bored"								,group:105	,accr:0},
{que:"＿い"					,ans:"いい"						,tip:"good"										,group:106	,accr:0},
{que:"嫌な"					,ans:"いやな"					,tip:"hateful"									,group:106	,accr:0},
{que:"美味しい"				,ans:"おいしい"					,tip:"delicious"								,group:107	,accr:0},
{que:"不味い"				,ans:"まずい"					,tip:"bad tasting"								,group:107	,accr:0},
{que:"大きい"				,ans:"おおきい"					,tip:"big"										,group:108	,accr:0},
{que:"小さい"				,ans:"ちいさい"					,tip:"small"									,group:108	,accr:0},
{que:"遅い"					,ans:"おそい"					,tip:"late"										,group:109	,accr:0},
{que:"早い"					,ans:"はやい"					,tip:"early"									,group:109	,accr:0},
{que:"速い"					,ans:"はやい"					,tip:"quick/fast"								,group:109	,accr:0},
{que:"重い"					,ans:"おもい"					,tip:"heavy"									,group:110	,accr:0},
{que:"軽い"					,ans:"かるい"					,tip:"light"									,group:110	,accr:0},
{que:"面白い"				,ans:"おもしろい"				,tip:"interesting"								,group:111	,accr:0},
{que:"詰まらない"			,ans:"つまらない"				,tip:"boring"									,group:111	,accr:0},
{que:"汚い"					,ans:"きたない"					,tip:"dirty"									,group:112	,accr:0},	//清い
{que:"綺麗な"				,ans:"きれいな"					,tip:"beautiful/clean"							,group:112	,accr:0},
{que:"近い"					,ans:"ちかい"					,tip:"near"										,group:113	,accr:0},
{que:"遠い"					,ans:"とおい"					,tip:"far"										,group:113	,accr:0},
{que:"長い"					,ans:"ながい"					,tip:"long"										,group:114	,accr:0},
{que:"短い"					,ans:"みじかい"					,tip:"short"									,group:114	,accr:0},
{que:"太い"					,ans:"ふとい"					,tip:"thick/fat"								,group:115	,accr:0},
{que:"細い"					,ans:"ほそい"					,tip:"thin/slim"								,group:115	,accr:0},
{que:"難しい"				,ans:"むずかしい"				,tip:"difficult"								,group:116	,accr:0},
{que:"易しい"				,ans:"やさしい"					,tip:"easy"										,group:116	,accr:0},
{que:"厚い"					,ans:"あつい"					,tip:"thick"									,group:117	,accr:0},
{que:"薄い"					,ans:"うすい"					,tip:"thin"										,group:117	,accr:0},
{que:"安全な"				,ans:"あんぜんな"				,tip:"safety"									,group:118	,accr:0},
{que:"危険な"				,ans:"きけんな"					,tip:"dangerous"								,group:118	,accr:0},
{que:"危ない"				,ans:"あぶない"					,tip:"dangerous"								,group:118	,accr:0},
{que:"嬉しい"				,ans:"うれしい"					,tip:"be glad"									,group:119	,accr:0},
{que:"悲しい"				,ans:"かなしい"					,tip:"sad"										,group:119	,accr:0},
{que:"深い"					,ans:"ふかい"					,tip:"deep"										,group:120	,accr:0},
{que:"浅い"					,ans:"あさい"					,tip:"shallow"									,group:120	,accr:0},
{que:"簡単な"				,ans:"かんたんな"				,tip:"simple/easy"								,group:121	,accr:0},
{que:"複雑な"				,ans:"ふくざつな"				,tip:"complicate"								,group:121	,accr:0},
{que:"明るい"				,ans:"あかるい"					,tip:"bright"									,group:0	,accr:0},	//暗い
{que:"痛い"					,ans:"いたい"					,tip:"painful"									,group:0	,accr:0},
{que:"辛い"					,ans:"からい"					,tip:"hot/spicy"								,group:0	,accr:0},	//甘い/苦い
{que:"可愛い"				,ans:"かわいい"					,tip:"cute"										,group:0	,accr:0},	//憎い
{que:"元気な"				,ans:"げんきな"					,tip:"energy/fine"								,group:0	,accr:0},
{que:"怖い"					,ans:"こわい"					,tip:"frightening/scary"						,group:0	,accr:0},
{que:"静かな"				,ans:"しずかな"					,tip:"quiet"									,group:0	,accr:0},	//騒がしい
{que:"狭い"					,ans:"せまい"					,tip:"narrow"									,group:0	,accr:0},	//広い
{que:"大切な"				,ans:"たいせつな"				,tip:"important"								,group:0	,accr:0},	//粗末
{que:"た＿＿い"				,ans:"たいてい"					,tip:"usually"									,group:0	,accr:0},
{que:"楽しい"				,ans:"たのしい"					,tip:"enjoyable"								,group:0	,accr:0},	//苦しい
{que:"大好きな"				,ans:"だいすきな"				,tip:"like very much"							,group:0	,accr:0},
{que:"強い"					,ans:"つよい"					,tip:"strong"									,group:0	,accr:0},	//弱い
{que:"賑やかな"				,ans:"にぎやかな"				,tip:"lively"									,group:0	,accr:0},	//寂しい/淋しい
{que:"低い"					,ans:"ひくい"					,tip:"low"										,group:0	,accr:0},	//高い
{que:"便利な"				,ans:"べんりな"					,tip:"convenience"								,group:0	,accr:0},	//不便
{que:"丸い/円い"			,ans:"まるい"					,tip:"round"									,group:0	,accr:0},	//四角い
{que:"安い"					,ans:"やすい"					,tip:"cheap"									,group:0	,accr:0},	//高い
{que:"有名な"				,ans:"ゆうめいな"				,tip:"famous"									,group:0	,accr:0},	//無名
{que:"立派な"				,ans:"りっぱな"					,tip:"splendid"									,group:0	,accr:0},	//粗末/貧弱
{que:"若い"					,ans:"わかい"					,tip:"young"									,group:0	,accr:0},	//老いた
{que:"悪い"					,ans:"わるい"					,tip:"bad"										,group:0	,accr:0},	//良い/好い/善い
{que:"上手い"				,ans:"うまい"					,tip:"skilful/good"								,group:0	,accr:0},
{que:"う＿＿い"				,ans:"うるさい"					,tip:"noisy"									,group:0	,accr:0},
{que:"美しい"				,ans:"うつくしい"				,tip:"beautiful"								,group:0	,accr:0},
{que:"厳しい"				,ans:"きびしい"					,tip:"strict"									,group:0	,accr:0},
{que:"臭い"					,ans:"くさい"					,tip:"smelly"									,group:0	,accr:0},
{que:"細かい"				,ans:"こまかい"					,tip:"fine"										,group:0	,accr:0},
{que:"残念な"				,ans:"ざんねんな"				,tip:"sorry"									,group:0	,accr:0},
{que:"十分"					,ans:"じゅうぶん"				,tip:"enough"									,group:0	,accr:0},
{que:"少ない"				,ans:"すくない"					,tip:"very few/little"							,group:0	,accr:0},
{que:"確かな"				,ans:"たしかな"					,tip:"surely"									,group:0	,accr:0},
{que:"小さな"				,ans:"ちいさな"					,tip:"small"									,group:0	,accr:0},
{que:"す＿い"				,ans:"すごい"					,tip:"fantastic/terrible"						,group:0	,accr:0},
{que:"特別な"				,ans:"とくべつな"				,tip:"special"									,group:0	,accr:0},
{que:"恥ずかしい"			,ans:"はずかしい"				,tip:"embarassing"								,group:0	,accr:0},
{que:"必要"					,ans:"ひつよう"					,tip:"necessary"								,group:0	,accr:0},
{que:"苦い"					,ans:"くるしい"					,tip:"painful"									,group:0	,accr:0},
{que:"熱心な"				,ans:"ねっしんな"				,tip:"eager"									,group:0	,accr:0},
{que:"真面目な"				,ans:"まじめな"					,tip:"serious"									,group:0	,accr:0},
{que:"無理な"				,ans:"むりな"					,tip:"impossible"								,group:0	,accr:0},
{que:"珍しい"				,ans:"めずらしい"				,tip:"unusual"									,group:0	,accr:0},
{que:"柔らかい"				,ans:"やわらかい"				,tip:"soft"										,group:0	,accr:0},
{que:"よ＿＿い"				,ans:"よろしい"					,tip:"good"										,group:0	,accr:0},
//-----------------------------------------------------N-----------------------------------------------------
{que:"明後日"				,ans:"あさって"					,tip:"the day after tomorrow"					,group:1001	,accr:0},
{que:"明日(＿＿＿)"			,ans:"あした"					,tip:"tomorrow"									,group:1001	,accr:0},
{que:"一昨日"				,ans:"おととい"					,tip:"the day before yesterday"					,group:1001	,accr:0},
{que:"昨日"					,ans:"きのう"					,tip:"yesterday"								,group:1001	,accr:0},
{que:"今日"					,ans:"きょう"					,tip:"today"									,group:1001	,accr:0},
{que:"毎日"					,ans:"まいにち"					,tip:"every day"								,group:1001	,accr:0},
{que:"奥さん"				,ans:"おくさん"					,tip:"(your) wife"								,group:1002	,accr:0},
{que:"家内"					,ans:"かない"					,tip:"(my) wife"								,group:1002	,accr:0},
{que:"兄"					,ans:"あに"						,tip:"(my) older brother"						,group:1003	,accr:0},
{que:"姉"					,ans:"あね"						,tip:"(my) older sister"						,group:1003	,accr:0},
{que:"弟"					,ans:"おとうと"					,tip:"(my) younger brother"						,group:1003	,accr:0},
{que:"妹"					,ans:"いもうと"					,tip:"(my) younger sister"						,group:1003	,accr:0},
{que:"お兄さん"				,ans:"おにいさん"				,tip:"(your) older brother"						,group:1003	,accr:0},
{que:"お姉さん"				,ans:"おねえさん"				,tip:"(your) older sister"						,group:1003	,accr:0},
{que:"お母さん"				,ans:"おかあさん"				,tip:"(your) mother"							,group:1004	,accr:0},
{que:"お父さん"				,ans:"おとうさん"				,tip:"(your) father"							,group:1004	,accr:0},
{que:"父"					,ans:"ちち"						,tip:"(my) father"								,group:1004	,accr:0},
{que:"母"					,ans:"はは"						,tip:"(my) mother"								,group:1004	,accr:0},
{que:"伯父"					,ans:"おじ"						,tip:"(my) uncle"								,group:1005	,accr:0},
{que:"伯母"					,ans:"おば"						,tip:"(my) aunt"								,group:1005	,accr:0},
{que:"お爺さん"				,ans:"おじいさん"				,tip:"(your) grand father"						,group:1006	,accr:0},
{que:"お婆さん"				,ans:"おばあさん"				,tip:"(your) grand mother"						,group:1006	,accr:0},
{que:"一昨年"				,ans:"おととし"					,tip:"the year before last"						,group:1007	,accr:0},
{que:"去年"					,ans:"きょねん"					,tip:"last year"								,group:1007	,accr:0},
{que:"今年"					,ans:"ことし"					,tip:"this year"								,group:1007	,accr:0},
{que:"さ来年"				,ans:"さらいねん"				,tip:"the year after next"						,group:1007	,accr:0},
{que:"毎年(ま＿＿ん)"		,ans:"まいねん"					,tip:"every year"								,group:1007	,accr:0},
{que:"毎年(ま＿＿し)"		,ans:"まいとし"					,tip:"every year"								,group:1007	,accr:0},
{que:"背(＿い)"				,ans:"せい"						,tip:"height"									,group:1008	,accr:0},
{que:"背(＿)"				,ans:"せ"						,tip:"height"									,group:1008	,accr:0},
{que:"毎月(ま＿＿つ)"		,ans:"まいげつ"					,tip:"every month"								,group:1009	,accr:0},
{que:"毎月(ま＿＿き)"		,ans:"まいつき"					,tip:"every month"								,group:1009	,accr:0},
{que:"東"					,ans:"ひがし"					,tip:"east"										,group:1010	,accr:0},
{que:"西"					,ans:"にし"						,tip:"west"										,group:1010	,accr:0},
{que:"南"					,ans:"みなみ"					,tip:"south"									,group:1010	,accr:0},
{que:"秋"					,ans:"あき"						,tip:"autumn/fall"								,group:1011	,accr:0},
{que:"夏"					,ans:"なつ"						,tip:"summer"									,group:1011	,accr:0},
{que:"春"					,ans:"はる"						,tip:"spring"									,group:1011	,accr:0},
{que:"冬"					,ans:"ふゆ"						,tip:"winter"									,group:1011	,accr:0},
{que:"子供"					,ans:"こども"					,tip:"child"									,group:1012	,accr:0},
{que:"大人"					,ans:"おとな"					,tip:"adult"									,group:1012	,accr:0},
{que:"男"					,ans:"おとこ"					,tip:"man"										,group:1013	,accr:0},
{que:"女"					,ans:"おんな"					,tip:"woman"									,group:1013	,accr:0},
{que:"男の子"				,ans:"おとこのこ"				,tip:"boy"										,group:1013	,accr:0},
{que:"女の子"				,ans:"おんなのこ"				,tip:"girl"										,group:1013	,accr:0},
{que:"朝"					,ans:"あさ"						,tip:"morning"									,group:0	,accr:0},
{que:"朝御飯"				,ans:"あさごはん"				,tip:"breakfast"								,group:0	,accr:0},
{que:"足"					,ans:"あし"						,tip:"leg/foot"									,group:0	,accr:0},
{que:"頭"					,ans:"あたま"					,tip:"head"										,group:0	,accr:0},
{que:"雨"					,ans:"あめ"						,tip:"rain"										,group:0	,accr:0},
{que:"家"					,ans:"いえ"						,tip:"house"									,group:0	,accr:0},
{que:"＿ち"					,ans:"うち"						,tip:"home"										,group:0	,accr:0},
{que:"池"					,ans:"いけ"						,tip:"pond"										,group:0	,accr:0},
{que:"医者"					,ans:"いしゃ"					,tip:"doctor"									,group:0	,accr:0},
{que:"椅子"					,ans:"いす"						,tip:"chair"									,group:0	,accr:0},
{que:"今"					,ans:"いま"						,tip:"now"										,group:0	,accr:0},
{que:"意味"					,ans:"いみ"						,tip:"meaning"									,group:0	,accr:0},
{que:"入り口"				,ans:"いりぐち"					,tip:"entrance"									,group:0	,accr:0},
{que:"色"					,ans:"いろ"						,tip:"color"									,group:0	,accr:0},
{que:"歌"					,ans:"うた"						,tip:"song"										,group:0	,accr:0},
{que:"海"					,ans:"うみ"						,tip:"sea"										,group:0	,accr:0},
{que:"映画"					,ans:"えいが"					,tip:"movie"									,group:0	,accr:0},
{que:"映画館"				,ans:"えいがかん"				,tip:"movie theater"							,group:0	,accr:0},
{que:"英語"					,ans:"えいご"					,tip:"English"									,group:0	,accr:0},
{que:"駅"					,ans:"えき"						,tip:"station"									,group:0	,accr:0},
{que:"円"					,ans:"えん"						,tip:"yen"										,group:0	,accr:0},
{que:"鉛筆"					,ans:"えんぴつ"					,tip:"pencil"									,group:0	,accr:0},
{que:"お菓子"				,ans:"おかし"					,tip:"snacks"									,group:0	,accr:0},
{que:"お金"					,ans:"おかね"					,tip:"money"									,group:0	,accr:0},
{que:"お酒"					,ans:"おさけ"					,tip:"liquor"									,group:0	,accr:0},
{que:"お皿"					,ans:"おさら"					,tip:"plate"									,group:0	,accr:0},
{que:"押し入れ"				,ans:"おしいれ"					,tip:"closet"									,group:0	,accr:0},
{que:"お茶"					,ans:"おちゃ"					,tip:"tea"										,group:0	,accr:0},
{que:"お手洗い"				,ans:"おてあらい"				,tip:"toilet"									,group:0	,accr:0},
{que:"お腹"					,ans:"おなか"					,tip:"stomach"									,group:0	,accr:0},
{que:"お弁当"				,ans:"おべんとう"				,tip:"lunch box"								,group:0	,accr:0},
{que:"音楽"					,ans:"おんがく"					,tip:"music"									,group:0	,accr:0},
{que:"会社"					,ans:"かいしゃ"					,tip:"company"									,group:0	,accr:0},
{que:"階段"					,ans:"かいだん"					,tip:"stairs"									,group:0	,accr:0},
{que:"買い物"				,ans:"かいもの"					,tip:"shopping"									,group:0	,accr:0},
{que:"顔"					,ans:"かお"						,tip:"face"										,group:0	,accr:0},
{que:"傘"					,ans:"かさ"						,tip:"umbrella"									,group:0	,accr:0},
{que:"風"					,ans:"かぜ"						,tip:"wind"										,group:0	,accr:0},
{que:"風邪"					,ans:"かぜ"						,tip:"cold"										,group:0	,accr:0},
{que:"家族"					,ans:"かぞく"					,tip:"family"									,group:0	,accr:0},
{que:"角"					,ans:"かど"						,tip:"corner"									,group:0	,accr:0},
{que:"鞄"					,ans:"かばん"					,tip:"bag"										,group:0	,accr:0},
{que:"花瓶"					,ans:"かびん"					,tip:"vase"										,group:0	,accr:0},
{que:"紙"					,ans:"かみ"						,tip:"paper"									,group:0	,accr:0},
{que:"体"					,ans:"からだ"					,tip:"body"										,group:0	,accr:0},
{que:"川/河"				,ans:"かわ"						,tip:"river"									,group:0	,accr:0},
{que:"漢字"					,ans:"かんじ"					,tip:"kanji"									,group:0	,accr:0},
{que:"外国"					,ans:"がいこく"					,tip:"foreign country"							,group:0	,accr:0},
{que:"外国人"				,ans:"がいこくじん"				,tip:"foreigner"								,group:0	,accr:0},
{que:"学生"					,ans:"がくせい"					,tip:"student"									,group:0	,accr:0},
{que:"学校"					,ans:"がっこう"					,tip:"school"									,group:0	,accr:0},
{que:"木"					,ans:"き"						,tip:"tree"										,group:0	,accr:0},
{que:"喫茶店"				,ans:"きっさてん"				,tip:"coffee shop"								,group:0	,accr:0},
{que:"切手"					,ans:"きって"					,tip:"stamps"									,group:0	,accr:0},
{que:"切符"					,ans:"きっぷ"					,tip:"ticket"									,group:0	,accr:0},
{que:"教室"					,ans:"きょうしつ"				,tip:"classroom"								,group:0	,accr:0},
{que:"兄弟"					,ans:"きょうだい"				,tip:"brother"									,group:0	,accr:0},
{que:"牛肉"					,ans:"ぎゅうにく"				,tip:"beef"										,group:0	,accr:0},
{que:"牛乳"					,ans:"ぎゅうにゅう"				,tip:"milk"										,group:0	,accr:0},
{que:"銀行"					,ans:"ぎんこう"					,tip:"bank"										,group:0	,accr:0},
{que:"薬"					,ans:"くすり"					,tip:"medicine"									,group:0	,accr:0},
{que:"果物"					,ans:"くだもの"					,tip:"fruit"									,group:0	,accr:0},
{que:"口"					,ans:"くち"						,tip:"mouth"									,group:0	,accr:0},
{que:"靴"					,ans:"くつ"						,tip:"shoes"									,group:0	,accr:0},
{que:"靴下"					,ans:"くつした"					,tip:"socks"									,group:0	,accr:0},
{que:"国"					,ans:"くに"						,tip:"country"									,group:0	,accr:0},
{que:"車"					,ans:"くるま"					,tip:"car"										,group:0	,accr:0},
{que:"玄関"					,ans:"げんかん"					,tip:"entrance hall"							,group:0	,accr:0},
{que:"公園"					,ans:"こうえん"					,tip:"park"										,group:0	,accr:0},
{que:"交番"					,ans:"こうばん"					,tip:"police box"								,group:0	,accr:0},
{que:"言葉"					,ans:"ことば"					,tip:"language"									,group:0	,accr:0},
{que:"今月"					,ans:"こんげつ"					,tip:"this months"								,group:0	,accr:0},
{que:"今週"					,ans:"こんしゅう"				,tip:"this week"								,group:0	,accr:0},
{que:"午後"					,ans:"ごご"						,tip:"P.M."										,group:0	,accr:0},
{que:"午前"					,ans:"ごぜん"					,tip:"A.M."										,group:0	,accr:0},
{que:"御飯"					,ans:"ごはん"					,tip:"meal/rice"								,group:0	,accr:0},
{que:"魚"					,ans:"さかな"					,tip:"fish"										,group:0	,accr:0},
{que:"作文"					,ans:"さくぶん"					,tip:"essay"									,group:0	,accr:0},
{que:"散歩"					,ans:"さんぽ"					,tip:"take a walk"								,group:0	,accr:0},
{que:"雑誌"					,ans:"ざっし"					,tip:"magazine"									,group:0	,accr:0},
{que:"仕事"					,ans:"しごと"					,tip:"work"										,group:0	,accr:0},
{que:"質問"					,ans:"しつもん"					,tip:"question"									,group:0	,accr:0},
{que:"写真"					,ans:"しゃしん"					,tip:"photograph"								,group:0	,accr:0},
{que:"宿題"					,ans:"しゅくだい"				,tip:"homework"									,group:0	,accr:0},
{que:"新聞"					,ans:"しんぶん"					,tip:"newspaper"								,group:0	,accr:0},
{que:"時"					,ans:"じ"						,tip:"o’clock"									,group:0	,accr:0},
{que:"時間"					,ans:"じかん"					,tip:"time/hour"								,group:0	,accr:0},
{que:"辞書"					,ans:"じしょ"					,tip:"dictionary"								,group:0	,accr:0},
{que:"自転車"				,ans:"じてんしゃ"				,tip:"bicycle"									,group:0	,accr:0},
{que:"自動車"				,ans:"じどうしゃ"				,tip:"car"										,group:0	,accr:0},
{que:"自分"					,ans:"じぶん"					,tip:"oneself"									,group:0	,accr:0},
{que:"授業"					,ans:"じゅぎょう"				,tip:"class"									,group:0	,accr:0},
{que:"生徒"					,ans:"せいと"					,tip:"student"									,group:0	,accr:0},
{que:"先月"					,ans:"せんげつ"					,tip:"last month"								,group:0	,accr:0},
{que:"先週"					,ans:"せんしゅう"				,tip:"last week"								,group:0	,accr:0},
{que:"先生"					,ans:"せんせい"					,tip:"teacher"									,group:0	,accr:0},
{que:"洗濯"					,ans:"せんたく"					,tip:"washing (for clothes)"					,group:0	,accr:0},
{que:"掃除"					,ans:"そうじ"					,tip:"cleaning"									,group:0	,accr:0},
{que:"大使館"				,ans:"たいしかん"				,tip:"embassy"									,group:0	,accr:0},
{que:"建物"					,ans:"たてもの"					,tip:"building"									,group:0	,accr:0},
{que:"食べ物"				,ans:"たべもの"					,tip:"food"										,group:0	,accr:0},
{que:"卵"					,ans:"たまご"					,tip:"egg"										,group:0	,accr:0},
{que:"誕生日"				,ans:"たんじょうび"				,tip:"birthday"									,group:0	,accr:0},
{que:"大学"					,ans:"だいがく"					,tip:"university"								,group:0	,accr:0},
{que:"台所"					,ans:"だいどころ"				,tip:"kitchen"									,group:0	,accr:0},
{que:"地下鉄"				,ans:"ちかてつ"					,tip:"subway"									,group:0	,accr:0},
{que:"地図"					,ans:"ちず"						,tip:"map"										,group:0	,accr:0},
{que:"茶色"					,ans:"ちゃいろ"					,tip:"brown"									,group:0	,accr:0},
{que:"手"					,ans:"て"						,tip:"hand"										,group:0	,accr:0},
{que:"手紙"					,ans:"てがみ"					,tip:"letter"									,group:0	,accr:0},
{que:"天気"					,ans:"てんき"					,tip:"weather"									,group:0	,accr:0},
{que:"出口"					,ans:"でぐち"					,tip:"exit"										,group:0	,accr:0},
{que:"電気"					,ans:"でんき"					,tip:"electricity"								,group:0	,accr:0},
{que:"電車"					,ans:"でんしゃ"					,tip:"train"									,group:0	,accr:0},
{que:"電話"					,ans:"でんわ"					,tip:"telephone"								,group:0	,accr:0},
{que:"戸"					,ans:"と"						,tip:"door"										,group:0	,accr:0},
{que:"時計"					,ans:"とけい"					,tip:"clock/watch"								,group:0	,accr:0},
{que:"所"					,ans:"ところ"					,tip:"place"									,group:0	,accr:0},
{que:"図書館"				,ans:"としょかん"				,tip:"library"									,group:0	,accr:0},
{que:"隣"					,ans:"となり"					,tip:"next door"								,group:0	,accr:0},
{que:"友達"					,ans:"ともだち"					,tip:"friend"									,group:0	,accr:0},
{que:"鳥"					,ans:"とり"						,tip:"bird"										,group:0	,accr:0},
{que:"鶏肉"					,ans:"とりにく"					,tip:"chicken"									,group:0	,accr:0},
{que:"動物"					,ans:"どうぶつ"					,tip:"animal"									,group:0	,accr:0},
{que:"夏休み"				,ans:"なつやすみ"				,tip:"summer vacation"							,group:0	,accr:0},
{que:"名前"					,ans:"なまえ"					,tip:"name"										,group:0	,accr:0},
{que:"肉"					,ans:"にく"						,tip:"meat"										,group:0	,accr:0},
{que:"日(＿ち)"				,ans:"にち"						,tip:"day"										,group:0	,accr:0},
{que:"荷物"					,ans:"にもつ"					,tip:"baggage"									,group:0	,accr:0},
{que:"庭"					,ans:"にわ"						,tip:"garden"									,group:0	,accr:0},
{que:"飲み物"				,ans:"のみもの"					,tip:"drinks"									,group:0	,accr:0},
{que:"歯"					,ans:"は"						,tip:"teeth"									,group:0	,accr:0},
{que:"灰皿"					,ans:"はいざら"					,tip:"ashtray"									,group:0	,accr:0},
{que:"箱"					,ans:"はこ"						,tip:"box"										,group:0	,accr:0},
{que:"橋"					,ans:"はし"						,tip:"bridge"									,group:0	,accr:0},
{que:"箸"					,ans:"はし"						,tip:"chopsticks"								,group:0	,accr:0},
{que:"花"					,ans:"はな"						,tip:"flower"									,group:0	,accr:0},
{que:"鼻"					,ans:"はな"						,tip:"nose"										,group:0	,accr:0},
{que:"話"					,ans:"はなし"					,tip:"story/speech"								,group:0	,accr:0},
{que:"晩"					,ans:"ばん"						,tip:"evening/night"							,group:0	,accr:0},
{que:"番号"					,ans:"ばんごう"					,tip:"number"									,group:0	,accr:0},
{que:"晩御飯"				,ans:"ばんごはん"				,tip:"dinner"									,group:0	,accr:0},
{que:"飛行機"				,ans:"ひこうき"					,tip:"airplane"									,group:0	,accr:0},
{que:"左"					,ans:"ひだり"					,tip:"left"										,group:0	,accr:0},
{que:"人"					,ans:"ひと"						,tip:"human/person"								,group:0	,accr:0},
{que:"平仮名"				,ans:"ひらがな"					,tip:"hiragana"									,group:0	,accr:0},
{que:"昼"					,ans:"ひる"						,tip:"noon"										,group:0	,accr:0},
{que:"昼御飯"				,ans:"ひるごはん"				,tip:"lunch"									,group:0	,accr:0},
{que:"病院"					,ans:"びょういん"				,tip:"hospital"									,group:0	,accr:0},
{que:"病気"					,ans:"びょうき"					,tip:"illness/sick"								,group:0	,accr:0},
{que:"封筒"					,ans:"ふうとう"					,tip:"envelop"									,group:0	,accr:0},
{que:"服"					,ans:"ふく"						,tip:"clothes"									,group:0	,accr:0},
{que:"風呂"					,ans:"ふろ"						,tip:"bath"										,group:0	,accr:0},
{que:"豚肉"					,ans:"ぶたにく"					,tip:"pork"										,group:0	,accr:0},
{que:"部屋"					,ans:"へや"						,tip:"room"										,group:0	,accr:0},
{que:"勉強"					,ans:"べんきょう"				,tip:"study"									,group:0	,accr:0},
{que:"本"					,ans:"ほん"						,tip:"book"										,group:0	,accr:0},
{que:"本棚"					,ans:"ほんだな"					,tip:"bookshelf"								,group:0	,accr:0},
{que:"帽子"					,ans:"ぼうし"					,tip:"hat/cap"									,group:0	,accr:0},
{que:"毎朝"					,ans:"まいあさ"					,tip:"every morning"							,group:0	,accr:0},
{que:"毎週"					,ans:"まいしゅう"				,tip:"every week"								,group:0	,accr:0},
{que:"毎晩"					,ans:"まいばん"					,tip:"every night"								,group:0	,accr:0},
{que:"町"					,ans:"まち"						,tip:"town/city"								,group:0	,accr:0},
{que:"窓"					,ans:"まど"						,tip:"window"									,group:0	,accr:0},
{que:"万年筆"				,ans:"まんねんひつ"				,tip:"fountain pen"								,group:0	,accr:0},
{que:"右"					,ans:"みぎ"						,tip:"right"									,group:0	,accr:0},
{que:"水"					,ans:"みず"						,tip:"water"									,group:0	,accr:0},
{que:"店"					,ans:"みせ"						,tip:"store/shop"								,group:0	,accr:0},
{que:"道"					,ans:"みち"						,tip:"street"									,group:0	,accr:0},
{que:"耳"					,ans:"みみ"						,tip:"ear"										,group:0	,accr:0},
{que:"目"					,ans:"め"						,tip:"eye"										,group:0	,accr:0},
{que:"眼鏡"					,ans:"めがね"					,tip:"glasses"									,group:0	,accr:0},
{que:"門"					,ans:"もん"						,tip:"gate"										,group:0	,accr:0},
{que:"問題"					,ans:"もんだい"					,tip:"problem"									,group:0	,accr:0},
{que:"屋"					,ans:"や"						,tip:"store/shop"								,group:0	,accr:0},
{que:"八百屋"				,ans:"やおや"					,tip:"vegetable store"							,group:0	,accr:0},
{que:"野菜"					,ans:"やさい"					,tip:"vegetable"								,group:0	,accr:0},
{que:"休み"					,ans:"やすみ"					,tip:"holiday"									,group:0	,accr:0},
{que:"山"					,ans:"やま"						,tip:"mountain"									,group:0	,accr:0},
{que:"旅行"					,ans:"りょこう"					,tip:"travel"									,group:0	,accr:0},
{que:"冷蔵庫"				,ans:"れいぞうこ"				,tip:"refrigerator"								,group:0	,accr:0},
{que:"練習"					,ans:"れんしゅう"				,tip:"practice"									,group:0	,accr:0},
{que:"赤ん坊"				,ans:"あかんぼう"				,tip:"baby"										,group:0	,accr:0},
{que:"朝寝坊"				,ans:"あさねぼう"				,tip:"oversleep"								,group:0	,accr:0},
{que:"医学"					,ans:"いがく"					,tip:"medical"									,group:0	,accr:0},
{que:"石"					,ans:"いし"						,tip:"stone"									,group:0	,accr:0},
{que:"嘘"					,ans:"うそ"						,tip:"lie"										,group:0	,accr:0},
{que:"腕"					,ans:"うで"						,tip:"arm"										,group:0	,accr:0},
{que:"裏"					,ans:"うら"						,tip:"the back/the wrong side"					,group:0	,accr:0},
{que:"応接間"				,ans:"おうせつま"				,tip:"drawing room"								,group:0	,accr:0},
{que:"お金持ち"				,ans:"おかねもち"				,tip:"a rich person"							,group:0	,accr:0},
{que:"屋上"					,ans:"おくじょう"				,tip:"the roof top"								,group:0	,accr:0},
{que:"贈り物"				,ans:"おくりもの"				,tip:"gift"										,group:0	,accr:0},
{que:"お祭り"				,ans:"おまつり"					,tip:"festival"									,group:0	,accr:0},
{que:"お見舞い"				,ans:"おみまい"					,tip:"asking after (a persons health)"			,group:0	,accr:0},
{que:"海岸"					,ans:"かいがん"					,tip:"sea shore"								,group:0	,accr:0},
{que:"会議"					,ans:"かいぎ"					,tip:"meeting"									,group:0	,accr:0},
{que:"会話"					,ans:"かいわ"					,tip:"conversation"								,group:0	,accr:0},
{que:"鏡"					,ans:"かがみ"					,tip:"mirror"									,group:0	,accr:0},
{que:"看護婦"				,ans:"かんごふ"					,tip:"nurse"									,group:0	,accr:0},
{que:"学部"					,ans:"がくぶ"					,tip:"department of university"					,group:0	,accr:0},
{que:"規則"					,ans:"きそく"					,tip:"regulations"								,group:0	,accr:0},
{que:"絹"					,ans:"きぬ"						,tip:"silk"										,group:0	,accr:0},
{que:"客"					,ans:"きゃく"					,tip:"guest"									,group:0	,accr:0},
{que:"急行"					,ans:"きゅうこう"				,tip:"express train"							,group:0	,accr:0},
{que:"教育"					,ans:"きょういく"				,tip:"education"								,group:0	,accr:0},
{que:"教会"					,ans:"きょうかい"				,tip:"church"									,group:0	,accr:0},
{que:"競争"					,ans:"きょうそう"				,tip:"compete/competition"						,group:0	,accr:0},
{que:"近所"					,ans:"きんじょ"					,tip:"neighbor hood"							,group:0	,accr:0},
{que:"草"					,ans:"くさ"						,tip:"grass"									,group:0	,accr:0},
{que:"計画"					,ans:"けいかく"					,tip:"plan"										,group:0	,accr:0},
{que:"警官"					,ans:"けいかん"					,tip:"policeman"								,group:0	,accr:0},
{que:"経験"					,ans:"けいけん"					,tip:"experience"								,group:0	,accr:0},
{que:"警察"					,ans:"けいさつ"					,tip:"police"									,group:0	,accr:0},
{que:"経済"					,ans:"けいざい"					,tip:"economy"									,group:0	,accr:0},
{que:"景色"					,ans:"けしき"					,tip:"scenery"									,group:0	,accr:0},
{que:"け＿か"				,ans:"けんか"					,tip:"fight"									,group:0	,accr:0},
{que:"研究"					,ans:"けんきゅう"				,tip:"study/research"							,group:0	,accr:0},
{que:"研究室"				,ans:"けんきゅうしつ"			,tip:"study room"								,group:0	,accr:0},
{que:"原因"					,ans:"げんいん"					,tip:"cause"									,group:0	,accr:0},
{que:"郊外"					,ans:"こうがい"					,tip:"suburbs"									,group:0	,accr:0},
{que:"講義"					,ans:"こうぎ"					,tip:"lecture"									,group:0	,accr:0},
{que:"工業"					,ans:"こうぎょう"				,tip:"industry"									,group:0	,accr:0},
{que:"校長"					,ans:"こうちょう"				,tip:"principal"								,group:0	,accr:0},
{que:"公務員"				,ans:"こうむいん"				,tip:"public servant"							,group:0	,accr:0},
{que:"声"					,ans:"こえ"						,tip:"voice"									,group:0	,accr:0},
{que:"国際"					,ans:"こくさい"					,tip:"international"							,group:0	,accr:0},
{que:"小鳥"					,ans:"ことり"					,tip:"small bird"								,group:0	,accr:0},
{que:"米"					,ans:"こめ"						,tip:"rice"										,group:0	,accr:0},
{que:"＿み"					,ans:"ごみ"						,tip:"dust"										,group:0	,accr:0},
{que:"下着"					,ans:"したぎ"					,tip:"under wear"								,group:0	,accr:0},
{que:"失敗"					,ans:"しっぱい"					,tip:"failure/fail"								,group:0	,accr:0},
{que:"品物"					,ans:"しなもの"					,tip:"article/goods"							,group:0	,accr:0},
{que:"社会"					,ans:"しゃかい"					,tip:"society"									,group:0	,accr:0},
{que:"習慣"					,ans:"しゅうかん"				,tip:"habit/custom"								,group:0	,accr:0},
{que:"出席"					,ans:"しゅっせき"				,tip:"attend"									,group:0	,accr:0},
{que:"出発"					,ans:"しゅっぱつ"				,tip:"departure"								,group:0	,accr:0},
{que:"趣味"					,ans:"しゅみ"					,tip:"hobby"									,group:0	,accr:0},
{que:"紹介"					,ans:"しょうかい"				,tip:"introduce"								,group:0	,accr:0},
{que:"小学校"				,ans:"しょうがっこう"			,tip:"primary school"							,group:0	,accr:0},
{que:"正月"					,ans:"しょうがつ"				,tip:"new year’s day"							,group:0	,accr:0},
{que:"小説"					,ans:"しょうせつ"				,tip:"novel"									,group:0	,accr:0},
{que:"招待"					,ans:"しょうたい"				,tip:"invite"									,group:0	,accr:0},
{que:"承知"					,ans:"しょうち"					,tip:"consent/agree"							,group:0	,accr:0},
{que:"将来"					,ans:"しょうらい"				,tip:"future"									,group:0	,accr:0},
{que:"新聞社"				,ans:"しんぶんしゃ"				,tip:"newspaper office"							,group:0	,accr:0},
{que:"字"					,ans:"じ"						,tip:"character"								,group:0	,accr:0},
{que:"事故"					,ans:"じこ"						,tip:"accident"									,group:0	,accr:0},
{que:"地震"					,ans:"じしん"					,tip:"earthquake"								,group:0	,accr:0},
{que:"時代"					,ans:"じだい"					,tip:"age/period/generation"					,group:0	,accr:0},
{que:"辞典"					,ans:"じてん"					,tip:"dictionary"								,group:0	,accr:0},
{que:"人口"					,ans:"じんこう"					,tip:"population"								,group:0	,accr:0},
{que:"神社"					,ans:"じんじゃ"					,tip:"Shinto shrine"							,group:0	,accr:0},
{que:"水道"					,ans:"すいどう"					,tip:"water works"								,group:0	,accr:0},
{que:"数学"					,ans:"すうがく"					,tip:"mathematics"								,group:0	,accr:0},
{que:"西洋"					,ans:"せいよう"					,tip:"West/Western countries"					,group:0	,accr:0},
{que:"背広"					,ans:"せびろ"					,tip:"suit"										,group:0	,accr:0},
{que:"先輩"					,ans:"せんぱい"					,tip:"one’s senior"								,group:0	,accr:0},
{que:"相談"					,ans:"そうだん"					,tip:"consultation"								,group:0	,accr:0},
{que:"卒業"					,ans:"そつぎょう"				,tip:"graduation"								,group:0	,accr:0},
{que:"畳"					,ans:"たたみ"					,tip:"tatami mat"								,group:0	,accr:0},
{que:"棚"					,ans:"たな"						,tip:"shelf"									,group:0	,accr:0},
{que:"暖房"					,ans:"だんぼう"					,tip:"heating"									,group:0	,accr:0},
{que:"注意"					,ans:"ちゅうい"					,tip:"advise/pay attention"						,group:0	,accr:0},
{que:"中学校"				,ans:"ちゅうがっこう"			,tip:"junior high school"						,group:0	,accr:0},
{que:"注射"					,ans:"ちゅうしゃ"				,tip:"injection"								,group:0	,accr:0},
{que:"地理"					,ans:"ちり"						,tip:"geography/geographical features"			,group:0	,accr:0},
{que:"都合"					,ans:"つごう"					,tip:"circumstances/convenience"				,group:0	,accr:0},
{que:"手袋"					,ans:"てぶくろ"					,tip:"gloves"									,group:0	,accr:0},
{que:"天気予報"				,ans:"てんきよほう"				,tip:"weather forecast"							,group:0	,accr:0},
{que:"展覧会"				,ans:"てんらんかい"				,tip:"exhibition"								,group:0	,accr:0},
{que:"電灯"					,ans:"でんとう"					,tip:"light"									,group:0	,accr:0},
{que:"電報"					,ans:"でんぽう"					,tip:"telegram"									,group:0	,accr:0},
{que:"と＿や"				,ans:"とこや"					,tip:"barber"									,group:0	,accr:0},
{que:"特急"					,ans:"とっきゅう"				,tip:"special express"							,group:0	,accr:0},
{que:"道具"					,ans:"どうぐ"					,tip:"tool"										,group:0	,accr:0},
{que:"泥棒"					,ans:"どろぼう"					,tip:"robber"									,group:0	,accr:0},
{que:"入院"					,ans:"にゅういん"				,tip:"enter hospital"							,group:0	,accr:0},
{que:"入学"					,ans:"にゅうがく"				,tip:"enter a school"							,group:0	,accr:0},
{que:"人形"					,ans:"にんぎょう"				,tip:"doll"										,group:0	,accr:0},
{que:"歯医者"				,ans:"はいしゃ"					,tip:"dentist"									,group:0	,accr:0},
{que:"発音"					,ans:"はつおん"					,tip:"pronunciation"							,group:0	,accr:0},
{que:"花見"					,ans:"はなみ"					,tip:"go to see cherry blossoms"				,group:0	,accr:0},
{que:"番組"					,ans:"ばんぐみ"					,tip:"TV program"								,group:0	,accr:0},
{que:"反対"					,ans:"はんたい"					,tip:"against/opposite"							,group:0	,accr:0},
{que:"日(＿)"				,ans:"ひ"						,tip:"day"										,group:0	,accr:0},
{que:"火"					,ans:"ひ"						,tip:"fire"										,group:0	,accr:0},
{que:"引き出し"				,ans:"ひきだし"					,tip:"drawer"									,group:0	,accr:0},
{que:"＿げ"					,ans:"ひげ"						,tip:"mustache"									,group:0	,accr:0},
{que:"飛行場"				,ans:"ひこうじょう"				,tip:"airport"									,group:0	,accr:0},
{que:"美術館"				,ans:"びじゅつかん"				,tip:"art museum"								,group:0	,accr:0},
{que:"昼間"					,ans:"ひるま"					,tip:"day time"									,group:0	,accr:0},
{que:"復習"					,ans:"ふくしゅう"				,tip:"review"									,group:0	,accr:0},
{que:"普通"					,ans:"ふつう"					,tip:"normal"									,group:0	,accr:0},
{que:"ぶ＿う"				,ans:"ぶどう"					,tip:"grape"									,group:0	,accr:0},
{que:"布団"					,ans:"ふとん"					,tip:"bedclothes"								,group:0	,accr:0},
{que:"舟"					,ans:"ふね"						,tip:"boat"										,group:0	,accr:0},
{que:"船"					,ans:"ふね"						,tip:"ship"										,group:0	,accr:0},
{que:"プ＿＿＿ト"			,ans:"プレゼント"				,tip:"present"									,group:0	,accr:0},
{que:"文化"					,ans:"ぶんか"					,tip:"culture"									,group:0	,accr:0},
{que:"文学"					,ans:"ぶんがく"					,tip:"literature"								,group:0	,accr:0},
{que:"文法"					,ans:"ぶんぽう"					,tip:"grammar"									,group:0	,accr:0},
{que:"返事"					,ans:"へんじ"					,tip:"response"									,group:0	,accr:0},
{que:"貿易"					,ans:"ぼうえき"					,tip:"trading"									,group:0	,accr:0},
{que:"放送"					,ans:"ほうそう"					,tip:"broadcast"								,group:0	,accr:0},
{que:"法律"					,ans:"ほうりつ"					,tip:"law"										,group:0	,accr:0},
{que:"星"					,ans:"ほし"						,tip:"star"										,group:0	,accr:0},
{que:"翻訳"					,ans:"ほんやく"					,tip:"translation"								,group:0	,accr:0},
{que:"漫画"					,ans:"まんが"					,tip:"cartoon"									,group:0	,accr:0},
{que:"湖"					,ans:"みずうみ"					,tip:"lake"										,group:0	,accr:0},
{que:"味噌"					,ans:"みそ"						,tip:"miso"										,group:0	,accr:0},
{que:"昔"					,ans:"むかし"					,tip:"the old day"								,group:0	,accr:0},
{que:"虫"					,ans:"むし"						,tip:"insect"									,group:0	,accr:0},
{que:"息子"					,ans:"むすこ"					,tip:"son"										,group:0	,accr:0},
{que:"娘"					,ans:"むすめ"					,tip:"daughter"									,group:0	,accr:0},
{que:"村"					,ans:"むら"						,tip:"village"									,group:0	,accr:0},
{que:"無理"					,ans:"むり"						,tip:"impossible"								,group:0	,accr:0},
{que:"木綿"					,ans:"もめん"					,tip:"cotton"									,group:0	,accr:0},
{que:"約束"					,ans:"やくそく"					,tip:"promise"									,group:0	,accr:0},
{que:"湯"					,ans:"ゆ"						,tip:"hot water"								,group:0	,accr:0},
{que:"夕飯"					,ans:"ゆうはん"					,tip:"dinner"									,group:0	,accr:0},
{que:"輸出"					,ans:"ゆしゅつ"					,tip:"export"									,group:0	,accr:0},
{que:"指"					,ans:"ゆび"						,tip:"finger"									,group:0	,accr:0},
{que:"指輪"					,ans:"ゆびわ"					,tip:"ring"										,group:0	,accr:0},
{que:"夢"					,ans:"ゆめ"						,tip:"dream"									,group:0	,accr:0},
{que:"用"					,ans:"よう"						,tip:"business/errand"							,group:0	,accr:0},
{que:"用意"					,ans:"ようい"					,tip:"preparation"								,group:0	,accr:0},
{que:"用事"					,ans:"ようじ"					,tip:"business/errand"							,group:0	,accr:0},
{que:"予習"					,ans:"よしゅう"					,tip:"preview"									,group:0	,accr:0},
{que:"予定"					,ans:"よてい"					,tip:"plan"										,group:0	,accr:0},
{que:"予約"					,ans:"よやく"					,tip:"booking/reservation"						,group:0	,accr:0},
{que:"理由"					,ans:"りゆう"					,tip:"reason"									,group:0	,accr:0},
{que:"利用"					,ans:"りよう"					,tip:"use"										,group:0	,accr:0},
{que:"両方"					,ans:"りょうほう"				,tip:"both"										,group:0	,accr:0},
{que:"旅館"					,ans:"りょかん"					,tip:"ryokan"									,group:0	,accr:0},
{que:"留守"					,ans:"ゆす"						,tip:"out of home"								,group:0	,accr:0},
{que:"歴史"					,ans:"れきし"					,tip:"history"									,group:0	,accr:0},
{que:"連絡"					,ans:"れんらく"					,tip:"contacts"									,group:0	,accr:0},
{que:"訳"					,ans:"やく"						,tip:"translation"								,group:0	,accr:0},
{que:"忘れ物"				,ans:"わすれもの"				,tip:"thing left behind"						,group:0	,accr:0},
{que:"割合"					,ans:"わりあい"					,tip:"percentage"								,group:0	,accr:0},
//---------------------------------------------------OTHER---------------------------------------------------
{que:"い＿＿＿＿い"			,ans:"いらっしゃい"				,tip:"May I help you?"							,group:2001	,accr:0},
{que:"い＿＿＿＿＿＿せ"		,ans:"いらっしゃいませ"			,tip:"May I help you?"							,group:2001	,accr:0},
{que:"＿ぐ"					,ans:"すぐ"						,tip:"at once"									,group:2002	,accr:0},
{que:"す＿に"				,ans:"すぐに"					,tip:"at once"									,group:2002	,accr:0},
{que:"＿ゃ"					,ans:"じゃ"						,tip:"then/well"								,group:2003	,accr:0},
{que:"じ＿あ"				,ans:"じゃあ"					,tip:"then/well"								,group:2003	,accr:0},
{que:"そ＿＿は"				,ans:"それでは"					,tip:"then/well"								,group:2003	,accr:0},
{que:"＿は"					,ans:"では"						,tip:"See you again"							,group:2004	,accr:0},
{que:"＿た"					,ans:"また"						,tip:"See you again"							,group:2004	,accr:0},
{que:"い＿え"				,ans:"いいえ"					,tip:"Not at all."								,group:2005	,accr:0},
{que:"ど＿＿＿＿＿＿て"		,ans:"どういたしまして"			,tip:"Not at all."								,group:2005	,accr:0},
{que:"あ＿こ"				,ans:"あそこ"					,tip:"over there"								,group:2006	,accr:0},
{que:"＿の"					,ans:"あの"						,tip:"that"										,group:2006	,accr:0},
{que:"こ＿な"				,ans:"こんな"					,tip:"this kind of/like this"					,group:2006	,accr:0},
{que:"＿う"					,ans:"どう"						,tip:"how"										,group:2006	,accr:0},
{que:"＿こ"					,ans:"どこ"						,tip:"where"									,group:2006	,accr:0},
{que:"ど＿ら"				,ans:"どちら"					,tip:"which (from two)"							,group:2006	,accr:0},
{que:"ど＿た"				,ans:"どなた"					,tip:"who"										,group:2006	,accr:0},
{que:"＿の"					,ans:"どの"						,tip:"which one/who"							,group:2006	,accr:0},
{que:"＿れ"					,ans:"どれ"						,tip:"which (from three or more)"				,group:2006	,accr:0},
{que:"ど＿な"				,ans:"どんな"					,tip:"what kind of"								,group:2006	,accr:0},
{que:"後"					,ans:"あと"						,tip:"after/later"								,group:0	,accr:0},
{que:"あ＿り"				,ans:"あまり"					,tip:"not much"									,group:0	,accr:0},
{que:"幾つ"					,ans:"いくつ"					,tip:"how many"									,group:0	,accr:0},
{que:"幾ら"					,ans:"いくら"					,tip:"how much"									,group:0	,accr:0},
{que:"い＿＿＿＿す"			,ans:"いただきます"				,tip:"(Before you eat, you say this)"			,group:0	,accr:0},
{que:"一"					,ans:"いち"						,tip:"one"										,group:0	,accr:0},
{que:"一番"					,ans:"いちばん"					,tip:"the first"								,group:0	,accr:0},
{que:"一緒"					,ans:"いっしょ"					,tip:"together"									,group:0	,accr:0},
{que:"＿つ"					,ans:"いつ"						,tip:"when"										,group:0	,accr:0},
{que:"五日"					,ans:"いつか"					,tip:"fifth of month"							,group:0	,accr:0},
{que:"五つ"					,ans:"いつつ"					,tip:"five"										,group:0	,accr:0},
{que:"い＿も"				,ans:"いつも"					,tip:"always"									,group:0	,accr:0},
{que:"色々"					,ans:"いろいろ"					,tip:"various"									,group:0	,accr:0},
{que:"上"					,ans:"うえ"						,tip:"top"										,group:0	,accr:0},
{que:"後ろ"					,ans:"うしろ"					,tip:"back"										,group:0	,accr:0},
{que:"同じ"					,ans:"おなじ"					,tip:"same"										,group:0	,accr:0},
{que:"お＿＿＿＿＿す"		,ans:"おねがいします"			,tip:"Please~"									,group:0	,accr:0},
{que:"お＿＿＿＿＿＿＿す"	,ans:"おはようございます"		,tip:"Good morning."							,group:0	,accr:0},
{que:"お＿＿＿＿＿い"		,ans:"おやすみなさい"			,tip:"Good night."								,group:0	,accr:0},
{que:"回"					,ans:"かい"						,tip:"times"									,group:0	,accr:0},
{que:"階"					,ans:"かい"						,tip:"(counter for) floor"						,group:0	,accr:0},
{que:"結構です"				,ans:"けっこうです"				,tip:"fine/no thanks"							,group:0	,accr:0},
{que:"九日"					,ans:"ここのか"					,tip:"ninth of month"							,group:0	,accr:0},
{que:"九つ"					,ans:"ここのつ"					,tip:"nine"										,group:0	,accr:0},
{que:"こ＿＿＿そ"			,ans:"こちらこそ"				,tip:"So do I"									,group:0	,accr:0},
{que:"今日は"				,ans:"こんにちは"				,tip:"Good afternoon"							,group:0	,accr:0},
{que:"今晩は"				,ans:"こんばんは"				,tip:"Good evening."							,group:0	,accr:0},
{que:"ご＿＿＿＿＿＿＿た"	,ans:"ごちそうさまでした"		,tip:"Thanks for your meal"						,group:0	,accr:0},
{que:"ご＿＿＿＿い"			,ans:"ごめんなさい"				,tip:"Sorry."									,group:0	,accr:0},
{que:"さ＿＿ら"				,ans:"さよなら"					,tip:"Goodbye."									,group:0	,accr:0},
{que:"失礼します"			,ans:"しつれいします"			,tip:"Excuse me. Excuse me leaving early"		,group:0	,accr:0},
{que:"少し"					,ans:"すこし"					,tip:"a little"									,group:0	,accr:0},
{que:"す＿＿＿ん"			,ans:"すみません"				,tip:"Im sorry."								,group:0	,accr:0},
{que:"全部"					,ans:"ぜんぶ"					,tip:"all"										,group:0	,accr:0},
{que:"そ＿で"				,ans:"それで"					,tip:"and then"									,group:0	,accr:0},
{que:"＿ば"					,ans:"そば"						,tip:"next by"									,group:0	,accr:0},
{que:"そ＿＿ら"				,ans:"それから"					,tip:"after that"								,group:0	,accr:0},
{que:"た＿＿ん"				,ans:"たいへん"					,tip:"very"										,group:0	,accr:0},
{que:"た＿＿ん"				,ans:"たくさん"					,tip:"many/much"								,group:0	,accr:0},
{que:"た＿ん"				,ans:"たぶん"					,tip:"probably/maybe"							,group:0	,accr:0},
{que:"大丈夫"				,ans:"だいじょうぶ"				,tip:"All right"								,group:0	,accr:0},
{que:"だ＿＿ん"				,ans:"だんだん"					,tip:"gradually"								,group:0	,accr:0},
{que:"ち＿＿ど"				,ans:"ちょうど"					,tip:"just"										,group:0	,accr:0},
{que:"ち＿＿と"				,ans:"ちょっと"					,tip:"for a moment/a little"					,group:0	,accr:0},
{que:"次"					,ans:"つぎ"						,tip:"next"										,group:0	,accr:0},
{que:"＿も"					,ans:"でも"						,tip:"but"										,group:0	,accr:0},
{que:"ど＿＿＿＿＿く"		,ans:"どうぞよろしく"			,tip:"Thanks in advance(Please favor me)"		,group:0	,accr:0},
{que:"時々"					,ans:"ときどき"					,tip:"sometimes"								,group:0	,accr:0},
{que:"と＿も"				,ans:"とても"					,tip:"very"										,group:0	,accr:0},
{que:"度"					,ans:"ど"						,tip:"times/degree"								,group:0	,accr:0},
{que:"ど＿＿て"				,ans:"どうして"					,tip:"why"										,group:0	,accr:0},
{que:"ど＿ぞ"				,ans:"どうぞ"					,tip:"please"									,group:0	,accr:0},
{que:"あ＿＿＿＿＿＿＿＿す"	,ans:"ありがとうございます"		,tip:"Thank you very much."						,group:0	,accr:0},
{que:"中"					,ans:"なか"						,tip:"inside"									,group:0	,accr:0},
{que:"初め"					,ans:"はじめ"					,tip:"at the beginning"							,group:0	,accr:0},
{que:"初めて"				,ans:"はじめて"					,tip:"for the first time"						,group:0	,accr:0},
{que:"は＿＿＿＿て"			,ans:"はじめまして"				,tip:"Nice to meet you."						,group:0	,accr:0},
{que:"半分"					,ans:"はんぶん"					,tip:"half"										,group:0	,accr:0},
{que:"ほ＿＿＿に"			,ans:"ほんとうに"				,tip:"really"									,group:0	,accr:0},
{que:"枚"					,ans:"まい"						,tip:"counter for flat things)"					,group:0	,accr:0},
{que:"前"					,ans:"まえ"						,tip:"front"									,group:0	,accr:0},
{que:"前"					,ans:"まえ"						,tip:"ago/before"								,group:0	,accr:0},
{que:"＿た"					,ans:"また"						,tip:"also/again"								,group:0	,accr:0},
{que:"＿だ"					,ans:"まだ"						,tip:"still/yet"								,group:0	,accr:0},
{que:"ま＿＿ぐ"				,ans:"まっすぐ"					,tip:"straight"									,group:0	,accr:0},
{que:"六日"					,ans:"むいか"					,tip:"the sixth of month"						,group:0	,accr:0},
{que:"向こう"				,ans:"むこう"					,tip:"over there"								,group:0	,accr:0},
{que:"＿う"					,ans:"もう"						,tip:"already/yet"								,group:0	,accr:0},
{que:"も＿と"				,ans:"もっと"					,tip:"more"										,group:0	,accr:0},
{que:"も＿＿し"				,ans:"もしもし"					,tip:"hello(on the phone)"						,group:0	,accr:0},
{que:"も＿＿ん"				,ans:"もちろん"					,tip:"of course"								,group:0	,accr:0},
{que:"以下"					,ans:"いか"						,tip:"or less than/not more than"				,group:0	,accr:0},
{que:"以上"					,ans:"いじょう"					,tip:"more than/over"							,group:0	,accr:0},
{que:"い＿＿い"				,ans:"いっぱい"					,tip:"fill/full"								,group:0	,accr:0},
{que:"以内"					,ans:"いない"					,tip:"within"									,group:0	,accr:0},
{que:"員"					,ans:"いん"						,tip:"worker/one who work at"					,group:0	,accr:0},
{que:"＿ん"					,ans:"うん"						,tip:"yes/alright"								,group:0	,accr:0},
{que:"大勢"					,ans:"おおぜい"					,tip:"many/great number of"						,group:0	,accr:0},
{que:"お＿＿＿＿で"			,ans:"おかげさまで"				,tip:"Thanks to you."							,group:0	,accr:0},
{que:"お＿＿＿に"			,ans:"おだいじに"				,tip:"Take care of your self"					,group:0	,accr:0},
{que:"お＿＿＿る"			,ans:"おっしゃる"				,tip:"to say (polite)"							,group:0	,accr:0},
{que:"お＿＿＿＿＿＿た"		,ans:"おまたせしました"			,tip:"Sorry I kept you waiting."				,group:0	,accr:0},
{que:"お＿＿＿＿＿＿＿＿す"	,ans:"おめでとうございます"		,tip:"Congratulations."							,group:0	,accr:0},
{que:"か＿＿＿＿＿＿た"		,ans:"かしこまりました"			,tip:"Certainly sir."							,group:0	,accr:0},
{que:"必ず"					,ans:"かならず"					,tip:"certainly/ever/always"					,group:0	,accr:0},
{que:"く＿い"				,ans:"くらい"					,tip:"about"									,group:0	,accr:0},
{que:"ぐ＿い"				,ans:"ぐらい"					,tip:"about"									,group:0	,accr:0},
{que:"決して"				,ans:"けっして"					,tip:"definitely/by no means/not at all"		,group:0	,accr:0},
{que:"け＿ど"				,ans:"けれど"					,tip:"but/however"								,group:0	,accr:0},
{que:"け＿＿も"				,ans:"けれども"					,tip:"but/however"								,group:0	,accr:0},
{que:"軒"					,ans:"けん"						,tip:"door"										,group:0	,accr:0},
{que:"個"					,ans:"こ"						,tip:"piece of"									,group:0	,accr:0},
{que:"こ＿ら"				,ans:"こちら"					,tip:"this side/this place"						,group:0	,accr:0},
{que:"こ＿ち"				,ans:"こっち"					,tip:"this way"									,group:0	,accr:0},
{que:"＿と"					,ans:"こと"						,tip:"thing"									,group:0	,accr:0},
{que:"こ＿＿＿だ"			,ans:"このあいだ"				,tip:"the other day/a few days ago"				,group:0	,accr:0},
{que:"こ＿＿ろ"				,ans:"このごろ"					,tip:"nowadays"									,group:0	,accr:0},
{que:"こ＿＿ら"				,ans:"これから"					,tip:"in future/hereafter"						,group:0	,accr:0},
{que:"ご存じ"				,ans:"ごぞんじ"					,tip:"know"										,group:0	,accr:0},
{que:"ご＿＿＿＿＿い"		,ans:"ごめんください"			,tip:"Hello! May I come in?"					,group:0	,accr:0},
{que:"し＿し"				,ans:"しかし"					,tip:"but"										,group:0	,accr:0},
{que:"し＿＿り"				,ans:"しっかり"					,tip:"firmly"									,group:0	,accr:0},
{que:"世話"					,ans:"せわ"						,tip:"take care of"								,group:0	,accr:0},
{que:"＿ひ"					,ans:"ぜひ"						,tip:"by some means/without fail"				,group:0	,accr:0},
{que:"ぜ＿＿ん"				,ans:"ぜんぜん"					,tip:"at all"									,group:0	,accr:0},
{que:"＿う"					,ans:"そう"						,tip:"so"										,group:0	,accr:0},
{que:"そ＿に"				,ans:"それに"					,tip:"besides/moreover"							,group:0	,accr:0},
{que:"そ＿＿＿＿＿＿＿ね"	,ans:"それはいけませんね"		,tip:"thats too bad."							,group:0	,accr:0},
{que:"そ＿＿ど"				,ans:"それほど"					,tip:"so/so much"								,group:0	,accr:0},
{que:"そ＿＿ろ"				,ans:"そろそろ"					,tip:"about the time to"						,group:0	,accr:0},
{que:"そ＿な"				,ans:"そんな"					,tip:"so/so much/like that"						,group:0	,accr:0},
{que:"例えば"				,ans:"たとえば"					,tip:"for example"								,group:0	,accr:0},
{que:"た＿に"				,ans:"たまに"					,tip:"occasionally"								,group:0	,accr:0},
{que:"＿め"					,ans:"ため"						,tip:"for/in order to"							,group:0	,accr:0},
{que:"だ＿＿い"				,ans:"だいたい"					,tip:"almost/general"							,group:0	,accr:0},
{que:"だ＿ら"				,ans:"だから"					,tip:"so/therefore"								,group:0	,accr:0},
{que:"お＿＿＿で"			,ans:"おげんきで"				,tip:"Take care."								,group:0	,accr:0},
{que:"ま＿は"				,ans:"または"					,tip:"or/the other"								,group:0	,accr:0},
{que:"や＿り"				,ans:"やはり"					,tip:"as I (you) thought/as I told you"			,group:0	,accr:0},
{que:"や＿＿り"				,ans:"やっぱり"					,tip:"as I (you) thought/as I told you"			,group:0	,accr:0},
{que:"ゆ＿＿り"				,ans:"ゆっくり"					,tip:"slowly"									,group:0	,accr:0},
{que:"合図"					,ans:"あいず"					,tip:"a signal"									,group:0	,accr:0},//N3 uncategory start
{que:"相手"					,ans:"あいて"					,tip:"a companion/a partner"					,group:0	,accr:0},
{que:"ア＿＿ア"				,ans:"アイデア"					,tip:"an idea"									,group:0	,accr:0},
{que:"ア＿＿ン"				,ans:"アイロン"					,tip:"an iron"									,group:0	,accr:0},
{que:"飽きる"				,ans:"あきる"					,tip:"to tire of"								,group:0	,accr:0},
{que:"握手"					,ans:"あくしゅ"					,tip:"shaking hands/a handshake"				,group:0	,accr:0},
{que:"ア＿＿＿ン"			,ans:"アクション"				,tip:"action"									,group:0	,accr:0},
{que:"顎"					,ans:"あご"						,tip:"chin"										,group:0	,accr:0},
{que:"麻"					,ans:"あさ"						,tip:"a hemp"									,group:0	,accr:0},
{que:"足首"					,ans:"あしくび"					,tip:"an ankle"									,group:0	,accr:0},
{que:"明日(＿＿)"			,ans:"あす"						,tip:"tomorrow"									,group:0	,accr:0},
{que:"預かる"				,ans:"あずかる"					,tip:"keep/look after something"				,group:0	,accr:0},
{que:"遊び"					,ans:"あそび"					,tip:"to play/to have fun"						,group:0	,accr:0},
{que:"与える"				,ans:"あたえる"					,tip:"to give"									,group:0	,accr:0},
{que:"暖まる"				,ans:"あたたまる"				,tip:"to be warmed"								,group:0	,accr:0},
{que:"辺り"					,ans:"あたり"					,tip:"around"									,group:0	,accr:0},
{que:"当たり前"				,ans:"あたりまえ"				,tip:"common sense"								,group:0	,accr:0},
{que:"あっという間に"		,ans:"あっというまに"			,tip:"in (like) a flash"						,group:0	,accr:0},
{que:"ア＿プ"				,ans:"アップ"					,tip:"up"										,group:0	,accr:0},
{que:"集まり"				,ans:"あつまり"					,tip:"a crowd"									,group:0	,accr:0},
{que:"宛名"					,ans:"あてな"					,tip:"an addressee"								,group:0	,accr:0},
{que:"当てる"				,ans:"あてる"					,tip:"to guess/to hit/to allot"					,group:0	,accr:0},
{que:"ア＿＿＿ス"			,ans:"アドバイス"				,tip:"to advice "								,group:0	,accr:0},
{que:"穴"					,ans:"あな"						,tip:"a hole"									,group:0	,accr:0},
{que:"ア＿＿＿＿ー"			,ans:"アナウンサー"				,tip:"an announcer"								,group:0	,accr:0},
{que:"ア＿＿＿ス"			,ans:"アナウンス"				,tip:"an announcement"							,group:0	,accr:0},
{que:"ア＿メ"				,ans:"アニメ"					,tip:"an animation"								,group:0	,accr:0},
{que:"脂"					,ans:"あぶら"					,tip:"an oil"									,group:0	,accr:0},
{que:"ア＿＿＿ア"			,ans:"アマチュア"				,tip:"amature"									,group:0	,accr:0},
{que:"争う"					,ans:"あらそう"					,tip:"to compete/to argue/to dispute"			,group:0	,accr:0},
{que:"表す"					,ans:"あらわす"					,tip:"to express/to be shown"					,group:0	,accr:0},
{que:"ア＿＿ム"				,ans:"アルバム"					,tip:"an album"									,group:0	,accr:0},
{que:"合わせる"				,ans:"あわせる"					,tip:"to put (bring) together"					,group:0	,accr:0},
{que:"慌てる"				,ans:"あわてる"					,tip:"to be confused/flustered/flurried"		,group:0	,accr:0},
{que:"案外"					,ans:"あんがい"					,tip:"unexpected"								,group:0	,accr:0},
{que:"ア＿＿＿ト"			,ans:"アンケート"				,tip:"a questionnaire"							,group:0	,accr:0},
{que:"意外"					,ans:"いがい"					,tip:"unexpected"								,group:0	,accr:0},
{que:"怒り"					,ans:"いかり"					,tip:"an anger"									,group:0	,accr:0},
{que:"以後"					,ans:"いご"						,tip:"later"									,group:0	,accr:0},
{que:"イ＿＿ル"				,ans:"イコール"					,tip:"equal "									,group:0	,accr:0},
{que:"医師"					,ans:"いし"						,tip:"a doctor"									,group:0	,accr:0},
{que:"意地悪"				,ans:"いじわる"					,tip:"spite"									,group:0	,accr:0},
{que:"以前"					,ans:"いぜん"					,tip:"before"									,group:0	,accr:0},
{que:"悪戯"					,ans:"いたずら"					,tip:"mischief/an escapade"						,group:0	,accr:0},
{que:"傷める"				,ans:"いためる"					,tip:"to hurt"									,group:0	,accr:0},
{que:"一度に"				,ans:"いちどに"					,tip:"at once"									,group:0	,accr:0},
{que:"一生"					,ans:"いっしょう"				,tip:"one's (whole) life"						,group:0	,accr:0},
{que:"一体"					,ans:"いったい"					,tip:"on earth (e.g. who on earth?)"			,group:0	,accr:0},
{que:"い＿＿＿＿か"			,ans:"いつのまにか"				,tip:"Before one knows"							,group:0	,accr:0},
{que:"命"					,ans:"いのち"					,tip:"a life"									,group:0	,accr:0},
{que:"居間"					,ans:"いま"						,tip:"a living room"							,group:0	,accr:0},
{que:"イ＿＿ジ"				,ans:"イメージ"					,tip:"image"									,group:0	,accr:0},
{que:"苛々"					,ans:"いらいら"					,tip:"a fretfulness/a fussines"					,group:0	,accr:0},
{que:"医療費"				,ans:"いりょうひ"				,tip:"a medical expenses/a doctor's bill"		,group:0	,accr:0},
{que:"祝う"					,ans:"いわう"					,tip:"to celebrate"								,group:0	,accr:0},
{que:"イ＿ク"				,ans:"インク"					,tip:"ink"										,group:0	,accr:0},
{que:"印象"					,ans:"いんしょう"				,tip:"impression"								,group:0	,accr:0},
{que:"イ＿＿＿＿ト"			,ans:"インスタント"				,tip:"instant "									,group:0	,accr:0},
{que:"イ＿＿＿＿＿ト"		,ans:"インターネット"			,tip:"internet"									,group:0	,accr:0},
{que:"イ＿＿＿＿ー"			,ans:"インタビュー"				,tip:"interview"								,group:0	,accr:0},
{que:"ウ＿＿ス"				,ans:"ウイルス"					,tip:"a virus"									,group:0	,accr:0},
{que:"ウ＿＿＿ー"			,ans:"ウェーター"				,tip:"a waiter"									,group:0	,accr:0},
{que:"ウ＿＿＿＿ス"			,ans:"ウェートレス"				,tip:"a waitress "								,group:0	,accr:0},
{que:"う＿＿り"				,ans:"うっかり"					,tip:"carelessly"								,group:0	,accr:0},
{que:"映る"					,ans:"うつる"					,tip:"be reflected (mirrored in)"				,group:0	,accr:0},
{que:"美味い"				,ans:"うまい"					,tip:"delicious"								,group:0	,accr:0},
{que:"埋まる"				,ans:"うまる"					,tip:"to be filled (up with)"					,group:0	,accr:0},
{que:"産む"					,ans:"うむ"						,tip:"to bear"									,group:0	,accr:0},
{que:"羨ましい"				,ans:"うらやましい"				,tip:"jealously/enviously/covetously"			,group:0	,accr:0},
{que:"上着"					,ans:"うわぎ"					,tip:"a outer wear "							,group:0	,accr:0},
{que:"噂"					,ans:"うわさ"					,tip:"a rumour"									,group:0	,accr:0},
{que:"運賃"					,ans:"うんちん"					,tip:"a fare"									,group:0	,accr:0},
{que:"運転士"				,ans:"うんてんし"				,tip:"a driver/train driver"					,group:0	,accr:0},
{que:"エ＿＿ン"				,ans:"エアコン"					,tip:"an air‐conditioning"						,group:0	,accr:0},
{que:"影響"					,ans:"えいきょう"				,tip:"(an) influence"							,group:0	,accr:0},
{que:"栄養"					,ans:"えいよう"					,tip:"a nutrition"								,group:0	,accr:0},
{que:"描く"					,ans:"えがく"					,tip:"to draw"									,group:0	,accr:0},
{que:"駅員"					,ans:"えきいん"					,tip:"a station employee"						,group:0	,accr:0},
{que:"エ＿＿ー"				,ans:"エッセー"					,tip:"an essay "								,group:0	,accr:0},
{que:"エ＿＿＿ー"			,ans:"エネルギー"				,tip:"an energy"								,group:0	,accr:0},
{que:"襟"					,ans:"えり"						,tip:"the neck"									,group:0	,accr:0},
{que:"演歌"					,ans:"えんか"					,tip:"trad‐style Japanese popular song"			,group:0	,accr:0},
{que:"演劇"					,ans:"えんげき"					,tip:"a theatrical performance"					,group:0	,accr:0},
{que:"エ＿＿＿ア"			,ans:"エンジニア"				,tip:"an engineer"								,group:0	,accr:0},
{que:"演奏"					,ans:"えんそう"					,tip:"a (musical) performance"					,group:0	,accr:0},
{que:"遠慮"					,ans:"えんりょ"					,tip:"reserve"									,group:0	,accr:0},
{que:"追い越す"				,ans:"おいこす"					,tip:"to pass/to get ahead of somebody"			,group:0	,accr:0},
{que:"応援"					,ans:"おうえん"					,tip:"an aid/assistance/a support"				,group:0	,accr:0},
{que:"オ＿＿ン"				,ans:"オープン"					,tip:"to open"									,group:0	,accr:0},
{que:"可笑しい"				,ans:"おかしい"					,tip:"funny/strange"							,group:0	,accr:0},
{que:"奢る"					,ans:"おごる"					,tip:"to treat somebody to something"			,group:0	,accr:0},
{que:"押さえる"				,ans:"おさえる"					,tip:"to press"									,group:0	,accr:0},
{que:"お辞儀"				,ans:"おじぎ"					,tip:"to bow"									,group:0	,accr:0},
{que:"お＿＿＿＿＿し"		,ans:"おたまじゃくし"			,tip:"a tadpole"								,group:0	,accr:0},
{que:"お＿こ"				,ans:"おでこ"					,tip:"the forehead"								,group:0	,accr:0},
{que:"大人しい"				,ans:"おとなしい"				,tip:"shy/quiet"								,group:0	,accr:0},
{que:"踊り"					,ans:"おどり"					,tip:"to dance"									,group:0	,accr:0},
{que:"オ＿ラ"				,ans:"オペラ"					,tip:"an opera"									,group:0	,accr:0},
{que:"お孫さん"				,ans:"おまごさん"				,tip:"a grandchild"								,group:0	,accr:0},
{que:"思い出"				,ans:"おもいで"					,tip:"memories"									,group:0	,accr:0},
{que:"思いやる"				,ans:"おもいやる"				,tip:"to think of/to have in mind"				,group:0	,accr:0},
{que:"親指"					,ans:"おやゆび"					,tip:"a thumb"									,group:0	,accr:0},
{que:"折る"					,ans:"おる"						,tip:"to fold"									,group:0	,accr:0},
{que:"カ＿＿ン"				,ans:"カーテン"					,tip:"a curtain"								,group:0	,accr:0},
{que:"カ＿＿＿ト"			,ans:"カーペット"				,tip:"a carpet"									,group:0	,accr:0},
{que:"解決"					,ans:"かいけつ"					,tip:"solution/settlement"						,group:0	,accr:0},
{que:"改札口"				,ans:"かいさつぐち"				,tip:"a ticket gate"							,group:0	,accr:0},
{que:"会社員"				,ans:"かいしゃいん"				,tip:"office employee"							,group:0	,accr:0},
{que:"解釈"					,ans:"かいしゃく"				,tip:"interpretation/reading"					,group:0	,accr:0},
{que:"回数券"				,ans:"かいすうけん"				,tip:"a book (sheet) of tickets"				,group:0	,accr:0},
{que:"快速"					,ans:"かいそく"					,tip:"an express train"							,group:0	,accr:0},
{que:"懐中電灯"				,ans:"かいちゅうでんとう"		,tip:"an electric torch/a flashlight"			,group:0	,accr:0},
{que:"飼う"					,ans:"かう"						,tip:"to own pet"								,group:0	,accr:0},
{que:"画家"					,ans:"がか"						,tip:"a painter"								,group:0	,accr:0},
{que:"化学"					,ans:"かがく"					,tip:"a chemistry"								,group:0	,accr:0},
{que:"踵"					,ans:"かかと"					,tip:"the heel"									,group:0	,accr:0},
{que:"書留"					,ans:"かきとめ"					,tip:"a registered letter"						,group:0	,accr:0},
{que:"掻く"					,ans:"かく"						,tip:"to scratch"								,group:0	,accr:0},
{que:"嗅ぐ"					,ans:"かぐ"						,tip:"to smell"									,group:0	,accr:0},
{que:"家具"					,ans:"かぐ"						,tip:"a furniture"								,group:0	,accr:0},
{que:"各駅停車"				,ans:"かくえきていしゃ"			,tip:"a local train"							,group:0	,accr:0},
{que:"確認"					,ans:"かくにん"					,tip:"a confirmation"							,group:0	,accr:0},
{que:"学歴"					,ans:"がくれき"					,tip:"one's educational background"				,group:0	,accr:0},
{que:"歌劇"					,ans:"かげき"					,tip:"an opera"									,group:0	,accr:0},
{que:"掛け算"				,ans:"かけざん"					,tip:"multiplication"							,group:0	,accr:0},
{que:"囲む"					,ans:"かこむ"					,tip:"to surround/to encircle/to encompass"		,group:0	,accr:0},
{que:"重ねる"				,ans:"かさねる"					,tip:"to lay one upon another"					,group:0	,accr:0},
{que:"飾り"					,ans:"かざり"					,tip:"a decoration"								,group:0	,accr:0},
{que:"貸し"					,ans:"かし"						,tip:"to loan"									,group:0	,accr:0},
{que:"数える"				,ans:"かぞえる"					,tip:"to count"									,group:0	,accr:0},
{que:"型"					,ans:"かた"						,tip:"a type"									,group:0	,accr:0},
{que:"固い"					,ans:"かたい"					,tip:"hard"										,group:0	,accr:0},
{que:"課題"					,ans:"かだい"					,tip:"a topic"									,group:0	,accr:0},
{que:"勝ち"					,ans:"かち"						,tip:"a win"									,group:0	,accr:0},
{que:"カ＿プ"				,ans:"カップ"					,tip:"a cup"									,group:0	,accr:0},
{que:"カ＿＿ル"				,ans:"カップル"					,tip:"lovers"									,group:0	,accr:0},
{que:"活躍"					,ans:"かつやく"					,tip:"an activity"								,group:0	,accr:0},
{que:"家庭"					,ans:"かてい"					,tip:"a family"									,group:0	,accr:0},
{que:"家電製品"				,ans:"かでんせいひん"			,tip:"consumer electronics"						,group:0	,accr:0},
{que:"悲しみ"				,ans:"かなしみ"					,tip:"a sorrow"									,group:0	,accr:0},
{que:"か＿り"				,ans:"かなり"					,tip:"rather"									,group:0	,accr:0},
{que:"黴"					,ans:"かび"						,tip:"mold"										,group:0	,accr:0},
{que:"構う"					,ans:"かまう"					,tip:"to care about"							,group:0	,accr:0},
{que:"我慢"					,ans:"がまん"					,tip:"endurance/patience"						,group:0	,accr:0},
{que:"我慢強い"				,ans:"がまんづよい"				,tip:"patient"									,group:0	,accr:0},
{que:"カ＿＿＿ン"			,ans:"カメラマン"				,tip:"a camera man"								,group:0	,accr:0},
{que:"画面"					,ans:"がめん"					,tip:"a screen"									,group:0	,accr:0},
{que:"痒い"					,ans:"かゆい"					,tip:"itchy/itching"							,group:0	,accr:0},
{que:"ガ＿ス"				,ans:"ガラス"					,tip:"a glass"									,group:0	,accr:0},
{que:"皮"					,ans:"かわ"						,tip:"the skin/the integument"					,group:0	,accr:0},
{que:"乾く"					,ans:"かわく"					,tip:"to be dry"								,group:0	,accr:0},
{que:"缶"					,ans:"かん"						,tip:"a can"									,group:0	,accr:0},
{que:"環境"					,ans:"かんきょう"				,tip:"environment"								,group:0	,accr:0},
{que:"看護師"				,ans:"かんごし"					,tip:"(hospital) nurse"							,group:0	,accr:0},
{que:"感心"					,ans:"かんしん"					,tip:"an Admiration"							,group:0	,accr:0},
{que:"完成"					,ans:"かんせい"					,tip:"a completion"								,group:0	,accr:0},
{que:"感想"					,ans:"かんそう"					,tip:"one's thoughts"							,group:0	,accr:0},
{que:"感動"					,ans:"かんどう"					,tip:" being deeply moved"						,group:0	,accr:0},
{que:"キ＿＿＿ド"			,ans:"キーボード"				,tip:"a key board"								,group:0	,accr:0},
{que:"期間"					,ans:"きかん"					,tip:"a term/a period"							,group:0	,accr:0},
{que:"効く"					,ans:"きく"						,tip:"to have an effect on"						,group:0	,accr:0},
{que:"期限"					,ans:"きげん"					,tip:"a period (of time)"						,group:0	,accr:0},
{que:"帰国"					,ans:"きこく"					,tip:"return (come back) to one's country"		,group:0	,accr:0},
{que:"奇数"					,ans:"きすう"					,tip:"an odd (uneven) number"					,group:0	,accr:0},
{que:"帰宅"					,ans:"きたく"					,tip:"to go home"								,group:0	,accr:0},
{que:"き＿＿と"				,ans:"きちんと"					,tip:"accurately/exactly/precisely"				,group:0	,accr:0},
{que:"キ＿＿ン"				,ans:"キッチン"					,tip:"a kitchen"								,group:0	,accr:0},
{que:"き＿と"				,ans:"きっと"					,tip:"surely"									,group:0	,accr:0},
{que:"希望"					,ans:"きぼう"					,tip:"a hope"									,group:0	,accr:0},
{que:"基本"					,ans:"きほん"					,tip:"basic"									,group:0	,accr:0},
{que:"決まり"				,ans:"きまり"					,tip:"a settlement"								,group:0	,accr:0},
{que:"客室乗務員"			,ans:"きゃくしつじょうむいん"	,tip:"a cabin crew"								,group:0	,accr:0},
{que:"休憩"					,ans:"きゅうけい"				,tip:"rest/a break/recess"						,group:0	,accr:0},
{que:"休日"					,ans:"きゅうじつ"				,tip:"a holiday"								,group:0	,accr:0},
{que:"教員"					,ans:"きょういん"				,tip:"a teacher"								,group:0	,accr:0},
{que:"強調"					,ans:"きょうちょう"				,tip:"an emphasis"								,group:0	,accr:0},
{que:"共通"					,ans:"きょうつう"				,tip:"a common"									,group:0	,accr:0},
{que:"興味"					,ans:"きょうみ"					,tip:"an interest"								,group:0	,accr:0},
{que:"協力"					,ans:"きょうりょく"				,tip:"a cooperation"							,group:0	,accr:0},
{que:"距離"					,ans:"きょり"					,tip:"a distance"								,group:0	,accr:0},
{que:"ぎ＿＿り"				,ans:"ぎりぎり"					,tip:"just barely"								,group:0	,accr:0},
{que:"記録"					,ans:"きろく"					,tip:"a record"									,group:0	,accr:0},
{que:"銀行員"				,ans:"ぎんこういん"				,tip:"banker"									,group:0	,accr:0},
{que:"禁止"					,ans:"きんし"					,tip:"a prohibition/an inhibition/a ban"		,group:0	,accr:0},
{que:"緊張"					,ans:"きんちょう"				,tip:"a strain/tension"							,group:0	,accr:0},
{que:"ク＿ズ"				,ans:"クイズ"					,tip:"a quiz"									,group:0	,accr:0},
{space:"＿",verd:2021040816}
);
